// Code generated by go-swagger; DO NOT EDIT.

package repo_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// DescribeRepoSelectorsReader is a Reader for the DescribeRepoSelectors structure.
type DescribeRepoSelectorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeRepoSelectorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDescribeRepoSelectorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeRepoSelectorsOK creates a DescribeRepoSelectorsOK with default headers values
func NewDescribeRepoSelectorsOK() *DescribeRepoSelectorsOK {
	return &DescribeRepoSelectorsOK{}
}

/*DescribeRepoSelectorsOK handles this case with default header values.

DescribeRepoSelectorsOK describe repo selectors o k
*/
type DescribeRepoSelectorsOK struct {
	Payload *models.OpenpitrixDescribeRepoSelectorsResponse
}

func (o *DescribeRepoSelectorsOK) Error() string {
	return fmt.Sprintf("[GET /v1/repos/selectors][%d] describeRepoSelectorsOK  %+v", 200, o.Payload)
}

func (o *DescribeRepoSelectorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixDescribeRepoSelectorsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
