// Code generated by go-swagger; DO NOT EDIT.

package repo_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewModifyRepoParams creates a new ModifyRepoParams object
// with the default values initialized.
func NewModifyRepoParams() *ModifyRepoParams {
	var ()
	return &ModifyRepoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewModifyRepoParamsWithTimeout creates a new ModifyRepoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModifyRepoParamsWithTimeout(timeout time.Duration) *ModifyRepoParams {
	var ()
	return &ModifyRepoParams{

		timeout: timeout,
	}
}

// NewModifyRepoParamsWithContext creates a new ModifyRepoParams object
// with the default values initialized, and the ability to set a context for a request
func NewModifyRepoParamsWithContext(ctx context.Context) *ModifyRepoParams {
	var ()
	return &ModifyRepoParams{

		Context: ctx,
	}
}

// NewModifyRepoParamsWithHTTPClient creates a new ModifyRepoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewModifyRepoParamsWithHTTPClient(client *http.Client) *ModifyRepoParams {
	var ()
	return &ModifyRepoParams{
		HTTPClient: client,
	}
}

/*ModifyRepoParams contains all the parameters to send to the API endpoint
for the modify repo operation typically these are written to a http.Request
*/
type ModifyRepoParams struct {

	/*Body*/
	Body *models.OpenpitrixModifyRepoRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the modify repo params
func (o *ModifyRepoParams) WithTimeout(timeout time.Duration) *ModifyRepoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify repo params
func (o *ModifyRepoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify repo params
func (o *ModifyRepoParams) WithContext(ctx context.Context) *ModifyRepoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify repo params
func (o *ModifyRepoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify repo params
func (o *ModifyRepoParams) WithHTTPClient(client *http.Client) *ModifyRepoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify repo params
func (o *ModifyRepoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the modify repo params
func (o *ModifyRepoParams) WithBody(body *models.OpenpitrixModifyRepoRequest) *ModifyRepoParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the modify repo params
func (o *ModifyRepoParams) SetBody(body *models.OpenpitrixModifyRepoRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyRepoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
