// Code generated by go-swagger; DO NOT EDIT.

package repo_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// ModifyRepoReader is a Reader for the ModifyRepo structure.
type ModifyRepoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyRepoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyRepoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyRepoOK creates a ModifyRepoOK with default headers values
func NewModifyRepoOK() *ModifyRepoOK {
	return &ModifyRepoOK{}
}

/*ModifyRepoOK handles this case with default header values.

A successful response.
*/
type ModifyRepoOK struct {
	Payload *models.OpenpitrixModifyRepoResponse
}

func (o *ModifyRepoOK) Error() string {
	return fmt.Sprintf("[PATCH /v1/repos][%d] modifyRepoOK  %+v", 200, o.Payload)
}

func (o *ModifyRepoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixModifyRepoResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
