CREATE TABLE `vendor_verify_info` (
  `user_id` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `company_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `company_website` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `company_profile` text COLLATE utf8mb4_unicode_ci,
  `authorizer_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `authorizer_email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `authorizer_phone` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `bank_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `bank_account_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `bank_account_number` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'new, submitted,  passed, rejected',
  `reject_message` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `submit_time` timestamp NULL DEFAULT NULL,
  `status_time` timestamp NULL DEFAULT NULL,
  `approver` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `owner` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `owner_path` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`user_id`),
  KEY `vendor_name_idx` (`company_name`),
  KEY `vendor_company_website_idx` (`company_website`),
  KEY `vendor_authorizer_name_idx` (`authorizer_name`),
  KEY `vendor_status_idx` (`status`),
  KEY `vendor_submit_time_idx` (`submit_time`),
  KEY `vendor_status_time_idx` (`status_time`),
  KEY `vendor_authorizer_email_idx` (`authorizer_email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
