apiVersion: batch/v1
kind: Job
metadata:
  name: openpitrix-im-db-init-job
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    job: openpitrix-im-db-init
    version: ${IM_VERSION}
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: openpitrix
        job: openpitrix-im-db-init
        version: ${IM_VERSION}
      name: openpitrix-im-db-init
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.${NAMESPACE}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      containers:
      - command: ["/flyway/sql/ddl/ddl_init.sh", "-hopenpitrix-db.${NAMESPACE}.svc", "-uroot", "--connect-timeout=5"]
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        image: ${IM_FLYWAY_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        name: openpitrix-im-db-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
