# Copyright 2017 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

default:
	cd spec && make
	cd swagger-ui && make

clean:
	-cd spec && make clean
	-cd swagger-ui && make clean
