# Copyright 2018 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

version: '3'

services:
  openpitrix-db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./pkg/db/ddl:/docker-entrypoint-initdb.d
    ports:
     - "23306:3306" # for run test
    container_name: "openpitrix-test-db"

  openpitrix-repo-db-ctrl:
    image: boxfuse/flyway:5.0.7-alpine
    command: -url=jdbc:mysql://openpitrix-db/repo -user=root -password=${MYSQL_ROOT_PASSWORD} -validateOnMigrate=false migrate
    volumes:
      - ./pkg/db/schema/repo:/flyway/sql
    links:
      - openpitrix-db:openpitrix-db
    depends_on:
      - openpitrix-db
    container_name: "openpitrix-test-repo-db-ctrl"

  openpitrix-app-db-ctrl:
    image: boxfuse/flyway:5.0.7-alpine
    command: -url=jdbc:mysql://openpitrix-db/app -user=root -password=${MYSQL_ROOT_PASSWORD} -validateOnMigrate=false migrate
    volumes:
      - ./pkg/db/schema/app:/flyway/sql
    links:
      - openpitrix-db:openpitrix-db
    depends_on:
      - openpitrix-db
    container_name: "openpitrix-test-app-db-ctrl"

  openpitrix-runtime-db-ctrl:
    image: boxfuse/flyway:5.0.7-alpine
    command: -url=jdbc:mysql://openpitrix-db/runtime -user=root -password=${MYSQL_ROOT_PASSWORD} -validateOnMigrate=false migrate
    volumes:
      - ./pkg/db/schema/runtime:/flyway/sql
    links:
      - openpitrix-db:openpitrix-db
    depends_on:
      - openpitrix-db
    container_name: "openpitrix-test-runtime-db-ctrl"

  # job service
  openpitrix-job-db-ctrl:
    image: boxfuse/flyway:5.0.7-alpine
    command: -url=jdbc:mysql://openpitrix-db/cluster -user=root -password=${MYSQL_ROOT_PASSWORD} -validateOnMigrate=false migrate
    volumes:
      - ./pkg/db/schema/job:/flyway/sql
    links:
      - openpitrix-db:openpitrix-db
    depends_on:
      - openpitrix-db
    container_name: "openpitrix-test-job-db-ctrl"

  openpitrix-task-db-ctrl:
    image: boxfuse/flyway:5.0.7-alpine
    command: -url=jdbc:mysql://openpitrix-db/cluster -user=root -password=${MYSQL_ROOT_PASSWORD} -validateOnMigrate=false migrate
    volumes:
      - ./pkg/db/schema/task:/flyway/sql
    links:
      - openpitrix-db:openpitrix-db
    depends_on:
      - openpitrix-db
    container_name: "openpitrix-test-task-db-ctrl"

  openpitrix-cluster-db-ctrl:
    image: boxfuse/flyway:5.0.7-alpine
    command: -url=jdbc:mysql://openpitrix-db/cluster -user=root -password=${MYSQL_ROOT_PASSWORD} -validateOnMigrate=false migrate
    volumes:
      - ./pkg/db/schema/cluster:/flyway/sql
    links:
      - openpitrix-db:openpitrix-db
    depends_on:
      - openpitrix-db
    container_name: "openpitrix-test-cluster-db-ctrl"
