# Copyright 2017 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

FROM boxfuse/flyway:5.0.7-alpine

RUN apk add --no-cache mysql-client

COPY ./pkg/db/schema /flyway/sql
COPY ./pkg/db/ddl /flyway/sql/ddl
COPY ./pkg/db/scripts /flyway/sql/ddl
