FROM alpine:3.7
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

COPY ./* /usr/local/bin/

RUN apk add --update ca-certificates && \
    update-ca-certificates && \
    adduser -D -g openpitrix -u 1002 openpitrix && \
    chown -R openpitrix:openpitrix /usr/local/bin/
USER openpitrix

CMD ["sh"]
