# Copyright 2017 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

version: '3'

services:
  openpitrix-db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
      - ./pkg/db/ddl:/docker-entrypoint-initdb.d
    ports:
     - "13306:3306" # for unit-test & debug
    container_name: "openpitrix-db"
  openpitrix-etcd:
    image: "appcelerator/etcd"
    volumes:
      - ${DATA_PATH}/etcd:/data
    ports:
     - "12379:2379" # for unit-test & debug
    container_name: "openpitrix-etcd"
  openpitrix-api-gateway:
    build: .
    image: "openpitrix"
    command: "api-gateway"
    ports:
     - "9100:9100"
    links:
      - openpitrix-app-manager:openpitrix-app-manager
      - openpitrix-repo-manager:openpitrix-repo-manager
    container_name: "openpitrix-api-gateway"

  # repo service
  openpitrix-repo-manager:
    build: .
    image: "openpitrix"
    command: "repo-manager"
    links:
      - openpitrix-db:openpitrix-db
      - openpitrix-etcd:openpitrix-etcd
    depends_on:
      - openpitrix-repo-db-ctrl
      - openpitrix-etcd
    container_name: "openpitrix-repo-manager"
    environment:
      - OPENPITRIX_LOG_LEVEL=${OPENPITRIX_LOG_LEVEL}
      - OPENPITRIX_MYSQL_DATABASE=repo
  openpitrix-repo-indexer:
    build: .
    image: "openpitrix"
    command: "repo-indexer"
    links:
      - openpitrix-db:openpitrix-db
      - openpitrix-etcd:openpitrix-etcd
      - openpitrix-repo-manager:openpitrix-repo-manager
    depends_on:
      - openpitrix-repo-db-ctrl
      - openpitrix-etcd
    container_name: "openpitrix-repo-indexer"
    environment:
      - OPENPITRIX_LOG_LEVEL=${OPENPITRIX_LOG_LEVEL}
      - OPENPITRIX_MYSQL_DATABASE=repo
  openpitrix-repo-db-ctrl:
    image: boxfuse/flyway:5.0.7-alpine
    command: -url=jdbc:mysql://openpitrix-db/repo -user=root -password=${MYSQL_ROOT_PASSWORD} -validateOnMigrate=false migrate
    volumes:
      - ./pkg/db/schema/repo:/flyway/sql
    links:
      - openpitrix-db:openpitrix-db
    depends_on:
      - openpitrix-db
    container_name: "openpitrix-repo-db-ctrl"

  # app service
  openpitrix-app-manager:
    build: .
    image: "openpitrix"
    command: "app-manager"
    links:
      - openpitrix-db:openpitrix-db
      - openpitrix-etcd:openpitrix-etcd
    depends_on:
      - openpitrix-app-db-ctrl
      - openpitrix-etcd
    container_name: "openpitrix-app-manager"
    environment:
      - OPENPITRIX_LOG_LEVEL=${OPENPITRIX_LOG_LEVEL}
      - OPENPITRIX_MYSQL_DATABASE=app
  openpitrix-app-db-ctrl:
    image: boxfuse/flyway:5.0.7-alpine
    command: -url=jdbc:mysql://openpitrix-db/app -user=root -password=${MYSQL_ROOT_PASSWORD} -validateOnMigrate=false migrate
    volumes:
      - ./pkg/db/schema/app:/flyway/sql
    links:
      - openpitrix-db:openpitrix-db
    depends_on:
      - openpitrix-db
    container_name: "openpitrix-app-db-ctrl"
