// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixDeleteRuntimeEnvResponse openpitrix delete runtime env response
// swagger:model openpitrixDeleteRuntimeEnvResponse
type OpenpitrixDeleteRuntimeEnvResponse struct {

	// runtime env
	RuntimeEnv *OpenpitrixRuntimeEnv `json:"runtime_env,omitempty"`
}

// Validate validates this openpitrix delete runtime env response
func (m *OpenpitrixDeleteRuntimeEnvResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRuntimeEnv(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixDeleteRuntimeEnvResponse) validateRuntimeEnv(formats strfmt.Registry) error {

	if swag.IsZero(m.RuntimeEnv) { // not required
		return nil
	}

	if m.RuntimeEnv != nil {

		if err := m.RuntimeEnv.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("runtime_env")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixDeleteRuntimeEnvResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixDeleteRuntimeEnvResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixDeleteRuntimeEnvResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
