// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixCancelAppVersionResponse openpitrix cancel app version response
// swagger:model openpitrixCancelAppVersionResponse
type OpenpitrixCancelAppVersionResponse struct {

	// required, id of version canceled
	VersionID string `json:"version_id,omitempty"`
}

// Validate validates this openpitrix cancel app version response
func (m *OpenpitrixCancelAppVersionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixCancelAppVersionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixCancelAppVersionResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixCancelAppVersionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
