// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixStopClustersResponse openpitrix stop clusters response
// swagger:model openpitrixStopClustersResponse
type OpenpitrixStopClustersResponse struct {

	// ids of clusters stopped
	ClusterID []string `json:"cluster_id"`

	// job ids
	JobID []string `json:"job_id"`
}

// Validate validates this openpitrix stop clusters response
func (m *OpenpitrixStopClustersResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClusterID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateJobID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixStopClustersResponse) validateClusterID(formats strfmt.Registry) error {

	if swag.IsZero(m.ClusterID) { // not required
		return nil
	}

	return nil
}

func (m *OpenpitrixStopClustersResponse) validateJobID(formats strfmt.Registry) error {

	if swag.IsZero(m.JobID) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixStopClustersResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixStopClustersResponse) UnmarshalBinary(b []byte) error {
	var res OpenpitrixStopClustersResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
