// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OpenpitrixApp openpitrix app
// swagger:model openpitrixApp
type OpenpitrixApp struct {

	// active
	Active bool `json:"active,omitempty"`

	// app id
	AppID string `json:"app_id,omitempty"`

	// app version types
	AppVersionTypes string `json:"app_version_types,omitempty"`

	// category set
	CategorySet OpenpitrixAppCategorySet `json:"category_set"`

	// chart name
	ChartName string `json:"chart_name,omitempty"`

	// create time
	CreateTime strfmt.DateTime `json:"create_time,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// home
	Home string `json:"home,omitempty"`

	// icon
	Icon string `json:"icon,omitempty"`

	// keywords
	Keywords string `json:"keywords,omitempty"`

	// latest app version
	LatestAppVersion *OpenpitrixAppVersion `json:"latest_app_version,omitempty"`

	// maintainers
	Maintainers string `json:"maintainers,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// owner
	Owner string `json:"owner,omitempty"`

	// readme
	Readme string `json:"readme,omitempty"`

	// repo id
	RepoID string `json:"repo_id,omitempty"`

	// screenshots
	Screenshots string `json:"screenshots,omitempty"`

	// sources
	Sources string `json:"sources,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// status time
	StatusTime strfmt.DateTime `json:"status_time,omitempty"`

	// update time
	UpdateTime strfmt.DateTime `json:"update_time,omitempty"`
}

// Validate validates this openpitrix app
func (m *OpenpitrixApp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLatestAppVersion(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OpenpitrixApp) validateLatestAppVersion(formats strfmt.Registry) error {

	if swag.IsZero(m.LatestAppVersion) { // not required
		return nil
	}

	if m.LatestAppVersion != nil {

		if err := m.LatestAppVersion.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("latest_app_version")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OpenpitrixApp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenpitrixApp) UnmarshalBinary(b []byte) error {
	var res OpenpitrixApp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
