// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata/types/pilot.proto

package pbtypes // import "openpitrix.io/openpitrix/pkg/pb/metadata/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PilotConfig struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host"`
	ListenPort           int32    `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port"`
	LogLevel             string   `protobuf:"bytes,5,opt,name=log_level,json=logLevel,proto3" json:"log_level"`
	TlsListenPort        int32    `protobuf:"varint,6,opt,name=tls_listen_port,json=tlsListenPort,proto3" json:"tls_listen_port"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PilotConfig) Reset()         { *m = PilotConfig{} }
func (m *PilotConfig) String() string { return proto.CompactTextString(m) }
func (*PilotConfig) ProtoMessage()    {}
func (*PilotConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilot_c1dbc44484eb1580, []int{0}
}
func (m *PilotConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PilotConfig.Unmarshal(m, b)
}
func (m *PilotConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PilotConfig.Marshal(b, m, deterministic)
}
func (dst *PilotConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PilotConfig.Merge(dst, src)
}
func (m *PilotConfig) XXX_Size() int {
	return xxx_messageInfo_PilotConfig.Size(m)
}
func (m *PilotConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PilotConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PilotConfig proto.InternalMessageInfo

func (m *PilotConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PilotConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PilotConfig) GetListenPort() int32 {
	if m != nil {
		return m.ListenPort
	}
	return 0
}

func (m *PilotConfig) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *PilotConfig) GetTlsListenPort() int32 {
	if m != nil {
		return m.TlsListenPort
	}
	return 0
}

type PilotClientTLSConfig struct {
	CaCrtData            string   `protobuf:"bytes,1,opt,name=ca_crt_data,json=caCrtData,proto3" json:"ca_crt_data"`
	ClientCrtData        string   `protobuf:"bytes,2,opt,name=client_crt_data,json=clientCrtData,proto3" json:"client_crt_data"`
	ClientKeyData        string   `protobuf:"bytes,3,opt,name=client_key_data,json=clientKeyData,proto3" json:"client_key_data"`
	PilotServerName      string   `protobuf:"bytes,4,opt,name=pilot_server_name,json=pilotServerName,proto3" json:"pilot_server_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PilotClientTLSConfig) Reset()         { *m = PilotClientTLSConfig{} }
func (m *PilotClientTLSConfig) String() string { return proto.CompactTextString(m) }
func (*PilotClientTLSConfig) ProtoMessage()    {}
func (*PilotClientTLSConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilot_c1dbc44484eb1580, []int{1}
}
func (m *PilotClientTLSConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PilotClientTLSConfig.Unmarshal(m, b)
}
func (m *PilotClientTLSConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PilotClientTLSConfig.Marshal(b, m, deterministic)
}
func (dst *PilotClientTLSConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PilotClientTLSConfig.Merge(dst, src)
}
func (m *PilotClientTLSConfig) XXX_Size() int {
	return xxx_messageInfo_PilotClientTLSConfig.Size(m)
}
func (m *PilotClientTLSConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PilotClientTLSConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PilotClientTLSConfig proto.InternalMessageInfo

func (m *PilotClientTLSConfig) GetCaCrtData() string {
	if m != nil {
		return m.CaCrtData
	}
	return ""
}

func (m *PilotClientTLSConfig) GetClientCrtData() string {
	if m != nil {
		return m.ClientCrtData
	}
	return ""
}

func (m *PilotClientTLSConfig) GetClientKeyData() string {
	if m != nil {
		return m.ClientKeyData
	}
	return ""
}

func (m *PilotClientTLSConfig) GetPilotServerName() string {
	if m != nil {
		return m.PilotServerName
	}
	return ""
}

type PilotEndpoint struct {
	PilotId              string   `protobuf:"bytes,1,opt,name=pilot_id,json=pilotId,proto3" json:"pilot_id"`
	PilotHost            string   `protobuf:"bytes,2,opt,name=pilot_host,json=pilotHost,proto3" json:"pilot_host"`
	PilotPort            int32    `protobuf:"varint,3,opt,name=pilot_port,json=pilotPort,proto3" json:"pilot_port"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PilotEndpoint) Reset()         { *m = PilotEndpoint{} }
func (m *PilotEndpoint) String() string { return proto.CompactTextString(m) }
func (*PilotEndpoint) ProtoMessage()    {}
func (*PilotEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilot_c1dbc44484eb1580, []int{2}
}
func (m *PilotEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PilotEndpoint.Unmarshal(m, b)
}
func (m *PilotEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PilotEndpoint.Marshal(b, m, deterministic)
}
func (dst *PilotEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PilotEndpoint.Merge(dst, src)
}
func (m *PilotEndpoint) XXX_Size() int {
	return xxx_messageInfo_PilotEndpoint.Size(m)
}
func (m *PilotEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_PilotEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_PilotEndpoint proto.InternalMessageInfo

func (m *PilotEndpoint) GetPilotId() string {
	if m != nil {
		return m.PilotId
	}
	return ""
}

func (m *PilotEndpoint) GetPilotHost() string {
	if m != nil {
		return m.PilotHost
	}
	return ""
}

func (m *PilotEndpoint) GetPilotPort() int32 {
	if m != nil {
		return m.PilotPort
	}
	return 0
}

func init() {
	proto.RegisterType((*PilotConfig)(nil), "metadata.types.PilotConfig")
	proto.RegisterType((*PilotClientTLSConfig)(nil), "metadata.types.PilotClientTLSConfig")
	proto.RegisterType((*PilotEndpoint)(nil), "metadata.types.PilotEndpoint")
}

func init() { proto.RegisterFile("metadata/types/pilot.proto", fileDescriptor_pilot_c1dbc44484eb1580) }

var fileDescriptor_pilot_c1dbc44484eb1580 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x4d, 0x4b, 0x2b, 0x41,
	0x10, 0x64, 0xf3, 0xf5, 0xb2, 0x1d, 0x92, 0xf0, 0x86, 0x77, 0xd8, 0xa7, 0xa8, 0x21, 0x07, 0x09,
	0x1e, 0xb2, 0x07, 0x41, 0x04, 0x6f, 0x46, 0x41, 0x31, 0x48, 0x48, 0x3c, 0x79, 0x59, 0x26, 0xbb,
	0xe3, 0x66, 0xc8, 0x64, 0x66, 0x98, 0x6d, 0x82, 0xf9, 0x25, 0xfe, 0x0f, 0x7f, 0xa1, 0x6c, 0x4f,
	0x4c, 0x22, 0x9e, 0x76, 0xbb, 0xaa, 0xba, 0xa7, 0xba, 0x68, 0x38, 0x5a, 0x09, 0xe4, 0x19, 0x47,
	0x1e, 0xe3, 0xc6, 0x8a, 0x22, 0xb6, 0x52, 0x19, 0x1c, 0x5a, 0x67, 0xd0, 0xb0, 0xce, 0x37, 0x37,
	0x24, 0xae, 0xff, 0x11, 0x40, 0x6b, 0x52, 0xf2, 0x23, 0xa3, 0xdf, 0x64, 0xce, 0x3a, 0x50, 0x91,
	0x59, 0x14, 0xf4, 0x82, 0x41, 0x38, 0xad, 0xc8, 0x8c, 0x31, 0xa8, 0x2d, 0x4c, 0x81, 0x51, 0x85,
	0x10, 0xfa, 0x67, 0x67, 0xd0, 0x52, 0xb2, 0x40, 0xa1, 0x13, 0x6b, 0x1c, 0x46, 0xb5, 0x5e, 0x30,
	0xa8, 0x4f, 0xc1, 0x43, 0x13, 0xe3, 0x90, 0x1d, 0x43, 0xa8, 0x4c, 0x9e, 0x28, 0xb1, 0x16, 0x2a,
	0xaa, 0x53, 0x67, 0x53, 0x99, 0x7c, 0x5c, 0xd6, 0xec, 0x1c, 0xba, 0xa8, 0x8a, 0xe4, 0x70, 0x42,
	0x83, 0x26, 0xb4, 0x51, 0x15, 0xe3, 0xdd, 0x90, 0xfe, 0x67, 0x00, 0xff, 0xbc, 0x33, 0x25, 0x85,
	0xc6, 0x97, 0xf1, 0x6c, 0x6b, 0xf1, 0x14, 0x5a, 0x29, 0x4f, 0x52, 0x87, 0x49, 0xb9, 0xc7, 0xd6,
	0x6b, 0x98, 0xf2, 0x91, 0xc3, 0x3b, 0x8e, 0xbc, 0x7c, 0x20, 0xa5, 0x96, 0xbd, 0xc6, 0xbb, 0x6f,
	0x7b, 0xf8, 0xb7, 0x6e, 0x29, 0x36, 0x5e, 0x57, 0x3d, 0xd4, 0x3d, 0x89, 0x0d, 0xe9, 0x2e, 0xe0,
	0x2f, 0x25, 0x98, 0x14, 0xc2, 0xad, 0x85, 0x4b, 0x34, 0x5f, 0x09, 0x5a, 0x3a, 0x9c, 0x76, 0x89,
	0x98, 0x11, 0xfe, 0xcc, 0x57, 0xa2, 0xbf, 0x80, 0x36, 0x79, 0xbe, 0xd7, 0x99, 0x35, 0x52, 0x23,
	0xfb, 0x0f, 0x4d, 0xdf, 0xbc, 0x4b, 0xf5, 0x0f, 0xd5, 0x8f, 0x19, 0x3b, 0x01, 0xf0, 0xd4, 0x41,
	0xc0, 0x21, 0x21, 0x0f, 0x65, 0xca, 0x3b, 0x9a, 0x22, 0xaa, 0x52, 0x44, 0x9e, 0x2e, 0xe3, 0xb9,
	0xbd, 0x7e, 0xbd, 0x32, 0x56, 0x68, 0x2b, 0xd1, 0xc9, 0xf7, 0xa1, 0x34, 0xf1, 0xbe, 0x8a, 0xed,
	0x32, 0x8f, 0xed, 0x3c, 0xfe, 0x79, 0x06, 0x37, 0x76, 0x4e, 0xdf, 0x79, 0x83, 0x2e, 0xe1, 0xf2,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x8e, 0xd2, 0x49, 0x27, 0x02, 0x00, 0x00,
}
