// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata/types/pilot.proto

package pbtypes // import "openpitrix.io/openpitrix/pkg/pb/metadata/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PilotConfig struct {
	Id                     string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Host                   string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host"`
	ListenPort             int32    `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port"`
	LogLevel               string   `protobuf:"bytes,5,opt,name=log_level,json=logLevel,proto3" json:"log_level"`
	ForFrontgateListenPort int32    `protobuf:"varint,6,opt,name=for_frontgate_listen_port,json=forFrontgateListenPort,proto3" json:"for_frontgate_listen_port"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *PilotConfig) Reset()         { *m = PilotConfig{} }
func (m *PilotConfig) String() string { return proto.CompactTextString(m) }
func (*PilotConfig) ProtoMessage()    {}
func (*PilotConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilot_0298beb1f3b6d083, []int{0}
}
func (m *PilotConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PilotConfig.Unmarshal(m, b)
}
func (m *PilotConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PilotConfig.Marshal(b, m, deterministic)
}
func (dst *PilotConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PilotConfig.Merge(dst, src)
}
func (m *PilotConfig) XXX_Size() int {
	return xxx_messageInfo_PilotConfig.Size(m)
}
func (m *PilotConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PilotConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PilotConfig proto.InternalMessageInfo

func (m *PilotConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PilotConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PilotConfig) GetListenPort() int32 {
	if m != nil {
		return m.ListenPort
	}
	return 0
}

func (m *PilotConfig) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *PilotConfig) GetForFrontgateListenPort() int32 {
	if m != nil {
		return m.ForFrontgateListenPort
	}
	return 0
}

type PilotTLSConfig struct {
	CaCrtData            string   `protobuf:"bytes,1,opt,name=ca_crt_data,json=caCrtData,proto3" json:"ca_crt_data"`
	ServerCrtData        string   `protobuf:"bytes,2,opt,name=server_crt_data,json=serverCrtData,proto3" json:"server_crt_data"`
	ServerKeyData        string   `protobuf:"bytes,3,opt,name=server_key_data,json=serverKeyData,proto3" json:"server_key_data"`
	ClientCrtData        string   `protobuf:"bytes,4,opt,name=client_crt_data,json=clientCrtData,proto3" json:"client_crt_data"`
	ClientKeyData        string   `protobuf:"bytes,5,opt,name=client_key_data,json=clientKeyData,proto3" json:"client_key_data"`
	PilotServerName      string   `protobuf:"bytes,6,opt,name=pilot_server_name,json=pilotServerName,proto3" json:"pilot_server_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PilotTLSConfig) Reset()         { *m = PilotTLSConfig{} }
func (m *PilotTLSConfig) String() string { return proto.CompactTextString(m) }
func (*PilotTLSConfig) ProtoMessage()    {}
func (*PilotTLSConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilot_0298beb1f3b6d083, []int{1}
}
func (m *PilotTLSConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PilotTLSConfig.Unmarshal(m, b)
}
func (m *PilotTLSConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PilotTLSConfig.Marshal(b, m, deterministic)
}
func (dst *PilotTLSConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PilotTLSConfig.Merge(dst, src)
}
func (m *PilotTLSConfig) XXX_Size() int {
	return xxx_messageInfo_PilotTLSConfig.Size(m)
}
func (m *PilotTLSConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PilotTLSConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PilotTLSConfig proto.InternalMessageInfo

func (m *PilotTLSConfig) GetCaCrtData() string {
	if m != nil {
		return m.CaCrtData
	}
	return ""
}

func (m *PilotTLSConfig) GetServerCrtData() string {
	if m != nil {
		return m.ServerCrtData
	}
	return ""
}

func (m *PilotTLSConfig) GetServerKeyData() string {
	if m != nil {
		return m.ServerKeyData
	}
	return ""
}

func (m *PilotTLSConfig) GetClientCrtData() string {
	if m != nil {
		return m.ClientCrtData
	}
	return ""
}

func (m *PilotTLSConfig) GetClientKeyData() string {
	if m != nil {
		return m.ClientKeyData
	}
	return ""
}

func (m *PilotTLSConfig) GetPilotServerName() string {
	if m != nil {
		return m.PilotServerName
	}
	return ""
}

type PilotClientTLSConfig struct {
	CaCrtData            string   `protobuf:"bytes,1,opt,name=ca_crt_data,json=caCrtData,proto3" json:"ca_crt_data"`
	ClientCrtData        string   `protobuf:"bytes,2,opt,name=client_crt_data,json=clientCrtData,proto3" json:"client_crt_data"`
	ClientKeyData        string   `protobuf:"bytes,3,opt,name=client_key_data,json=clientKeyData,proto3" json:"client_key_data"`
	PilotServerName      string   `protobuf:"bytes,4,opt,name=pilot_server_name,json=pilotServerName,proto3" json:"pilot_server_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PilotClientTLSConfig) Reset()         { *m = PilotClientTLSConfig{} }
func (m *PilotClientTLSConfig) String() string { return proto.CompactTextString(m) }
func (*PilotClientTLSConfig) ProtoMessage()    {}
func (*PilotClientTLSConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilot_0298beb1f3b6d083, []int{2}
}
func (m *PilotClientTLSConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PilotClientTLSConfig.Unmarshal(m, b)
}
func (m *PilotClientTLSConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PilotClientTLSConfig.Marshal(b, m, deterministic)
}
func (dst *PilotClientTLSConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PilotClientTLSConfig.Merge(dst, src)
}
func (m *PilotClientTLSConfig) XXX_Size() int {
	return xxx_messageInfo_PilotClientTLSConfig.Size(m)
}
func (m *PilotClientTLSConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PilotClientTLSConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PilotClientTLSConfig proto.InternalMessageInfo

func (m *PilotClientTLSConfig) GetCaCrtData() string {
	if m != nil {
		return m.CaCrtData
	}
	return ""
}

func (m *PilotClientTLSConfig) GetClientCrtData() string {
	if m != nil {
		return m.ClientCrtData
	}
	return ""
}

func (m *PilotClientTLSConfig) GetClientKeyData() string {
	if m != nil {
		return m.ClientKeyData
	}
	return ""
}

func (m *PilotClientTLSConfig) GetPilotServerName() string {
	if m != nil {
		return m.PilotServerName
	}
	return ""
}

type PilotEndpoint struct {
	PilotId              string   `protobuf:"bytes,1,opt,name=pilot_id,json=pilotId,proto3" json:"pilot_id"`
	PilotHost            string   `protobuf:"bytes,2,opt,name=pilot_host,json=pilotHost,proto3" json:"pilot_host"`
	PilotPort            int32    `protobuf:"varint,3,opt,name=pilot_port,json=pilotPort,proto3" json:"pilot_port"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PilotEndpoint) Reset()         { *m = PilotEndpoint{} }
func (m *PilotEndpoint) String() string { return proto.CompactTextString(m) }
func (*PilotEndpoint) ProtoMessage()    {}
func (*PilotEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_pilot_0298beb1f3b6d083, []int{3}
}
func (m *PilotEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PilotEndpoint.Unmarshal(m, b)
}
func (m *PilotEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PilotEndpoint.Marshal(b, m, deterministic)
}
func (dst *PilotEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PilotEndpoint.Merge(dst, src)
}
func (m *PilotEndpoint) XXX_Size() int {
	return xxx_messageInfo_PilotEndpoint.Size(m)
}
func (m *PilotEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_PilotEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_PilotEndpoint proto.InternalMessageInfo

func (m *PilotEndpoint) GetPilotId() string {
	if m != nil {
		return m.PilotId
	}
	return ""
}

func (m *PilotEndpoint) GetPilotHost() string {
	if m != nil {
		return m.PilotHost
	}
	return ""
}

func (m *PilotEndpoint) GetPilotPort() int32 {
	if m != nil {
		return m.PilotPort
	}
	return 0
}

func init() {
	proto.RegisterType((*PilotConfig)(nil), "metadata.types.PilotConfig")
	proto.RegisterType((*PilotTLSConfig)(nil), "metadata.types.PilotTLSConfig")
	proto.RegisterType((*PilotClientTLSConfig)(nil), "metadata.types.PilotClientTLSConfig")
	proto.RegisterType((*PilotEndpoint)(nil), "metadata.types.PilotEndpoint")
}

func init() { proto.RegisterFile("metadata/types/pilot.proto", fileDescriptor_pilot_0298beb1f3b6d083) }

var fileDescriptor_pilot_0298beb1f3b6d083 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x14, 0x54, 0xd2, 0x74, 0xd9, 0xbc, 0x6a, 0xbb, 0xc2, 0x42, 0x28, 0x0b, 0x02, 0x56, 0x3d, 0xa0,
	0x8a, 0x43, 0x73, 0x40, 0x42, 0x20, 0x6e, 0x14, 0x10, 0x88, 0x0a, 0x55, 0x2d, 0x27, 0x2e, 0x91,
	0x9b, 0x38, 0xa9, 0xd5, 0xd4, 0xb6, 0x9c, 0xa7, 0x8a, 0xfe, 0x25, 0x8e, 0xfc, 0x3e, 0x0e, 0x28,
	0xcf, 0x49, 0x1a, 0x3e, 0x0e, 0xe5, 0xd4, 0xbe, 0x99, 0xf1, 0x64, 0x6c, 0x8f, 0xe1, 0xc1, 0x5e,
	0x20, 0xcf, 0x38, 0xf2, 0x18, 0x8f, 0x46, 0x54, 0xb1, 0x91, 0xa5, 0xc6, 0x99, 0xb1, 0x1a, 0x35,
	0x1b, 0xb7, 0xdc, 0x8c, 0xb8, 0xc9, 0x77, 0x0f, 0x46, 0xcb, 0x9a, 0x9f, 0x6b, 0x95, 0xcb, 0x82,
	0x8d, 0xc1, 0x97, 0x59, 0xe4, 0xdd, 0x7a, 0xd3, 0x70, 0xe5, 0xcb, 0x8c, 0x31, 0x08, 0xb6, 0xba,
	0xc2, 0xc8, 0x27, 0x84, 0xfe, 0xb3, 0x27, 0x30, 0x2a, 0x65, 0x85, 0x42, 0x25, 0x46, 0x5b, 0x8c,
	0x82, 0x5b, 0x6f, 0x3a, 0x5c, 0x81, 0x83, 0x96, 0xda, 0x22, 0x7b, 0x08, 0x61, 0xa9, 0x8b, 0xa4,
	0x14, 0x07, 0x51, 0x46, 0x43, 0x5a, 0x79, 0x59, 0xea, 0x62, 0x51, 0xcf, 0xec, 0x15, 0xdc, 0xe4,
	0xda, 0x26, 0xb9, 0xd5, 0x0a, 0x0b, 0x8e, 0x22, 0xe9, 0x7b, 0x5d, 0x90, 0xd7, 0xfd, 0x5c, 0xdb,
	0xf7, 0x2d, 0xbf, 0xe8, 0x7c, 0x27, 0x3f, 0x3d, 0x18, 0x53, 0xd8, 0x2f, 0x8b, 0x75, 0x93, 0xf7,
	0x31, 0x8c, 0x52, 0x9e, 0xa4, 0x16, 0x93, 0x7a, 0x53, 0x4d, 0xf0, 0x30, 0xe5, 0x73, 0x8b, 0x6f,
	0x39, 0x72, 0xf6, 0x14, 0xae, 0x2b, 0x61, 0x0f, 0xc2, 0x9e, 0x34, 0x6e, 0x2b, 0x57, 0x0e, 0xfe,
	0x5b, 0xb7, 0x13, 0x47, 0xa7, 0x1b, 0xf4, 0x75, 0x9f, 0xc4, 0xb1, 0xd5, 0xa5, 0xa5, 0x14, 0x0a,
	0x4f, 0x7e, 0x81, 0xd3, 0x39, 0xb8, 0xe7, 0xd7, 0xe8, 0x3a, 0xbf, 0x61, 0x5f, 0xd7, 0xfa, 0x3d,
	0x83, 0xbb, 0x74, 0x3d, 0x49, 0xf3, 0x75, 0xc5, 0xf7, 0x82, 0x4e, 0x21, 0x5c, 0x5d, 0x13, 0xb1,
	0x26, 0xfc, 0x33, 0xdf, 0x8b, 0xc9, 0x0f, 0x0f, 0xee, 0xb9, 0xbb, 0x22, 0x8b, 0xff, 0x3a, 0x84,
	0x3f, 0x43, 0xfb, 0x67, 0x86, 0x1e, 0x9c, 0x1d, 0x3a, 0xf8, 0x77, 0xe8, 0x2d, 0x5c, 0x51, 0xe6,
	0x77, 0x2a, 0x33, 0x5a, 0x2a, 0x64, 0x37, 0x70, 0xe9, 0x16, 0x77, 0x3d, 0xbb, 0x43, 0xf3, 0xc7,
	0x8c, 0x3d, 0x02, 0x70, 0x54, 0xaf, 0x72, 0x21, 0x21, 0x1f, 0xea, 0xde, 0x75, 0x34, 0x55, 0x65,
	0x40, 0x55, 0x71, 0x74, 0xdd, 0x8e, 0x37, 0x2f, 0xbf, 0xbe, 0xd0, 0x46, 0x28, 0x23, 0xd1, 0xca,
	0x6f, 0x33, 0xa9, 0xe3, 0xd3, 0x14, 0x9b, 0x5d, 0x11, 0x9b, 0x4d, 0xfc, 0xfb, 0xc3, 0x78, 0x6d,
	0x36, 0xf4, 0xbb, 0xb9, 0xa0, 0xb7, 0xf1, 0xfc, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xef,
	0x8c, 0xe5, 0x39, 0x03, 0x00, 0x00,
}
