// Code generated by go-swagger; DO NOT EDIT.

package runtime_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// DeleteRuntimesReader is a Reader for the DeleteRuntimes structure.
type DeleteRuntimesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRuntimesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteRuntimesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRuntimesOK creates a DeleteRuntimesOK with default headers values
func NewDeleteRuntimesOK() *DeleteRuntimesOK {
	return &DeleteRuntimesOK{}
}

/*DeleteRuntimesOK handles this case with default header values.

A successful response.
*/
type DeleteRuntimesOK struct {
	Payload *models.OpenpitrixDeleteRuntimesResponse
}

func (o *DeleteRuntimesOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/runtimes][%d] deleteRuntimesOK  %+v", 200, o.Payload)
}

func (o *DeleteRuntimesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixDeleteRuntimesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
