// Code generated by go-swagger; DO NOT EDIT.

package runtime_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// DescribeRuntimeProviderZonesReader is a Reader for the DescribeRuntimeProviderZones structure.
type DescribeRuntimeProviderZonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeRuntimeProviderZonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDescribeRuntimeProviderZonesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeRuntimeProviderZonesOK creates a DescribeRuntimeProviderZonesOK with default headers values
func NewDescribeRuntimeProviderZonesOK() *DescribeRuntimeProviderZonesOK {
	return &DescribeRuntimeProviderZonesOK{}
}

/*DescribeRuntimeProviderZonesOK handles this case with default header values.

A successful response.
*/
type DescribeRuntimeProviderZonesOK struct {
	Payload *models.OpenpitrixDescribeRuntimeProviderZonesResponse
}

func (o *DescribeRuntimeProviderZonesOK) Error() string {
	return fmt.Sprintf("[GET /v1/runtimes/zones][%d] describeRuntimeProviderZonesOK  %+v", 200, o.Payload)
}

func (o *DescribeRuntimeProviderZonesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixDescribeRuntimeProviderZonesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
