apiVersion: v1
kind: Service
metadata:
  name: openpitrix-im-service
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-im-service
    version: ${IM_VERSION}
spec:
  selector:
    app: openpitrix
    component: openpitrix-im-service
  ports:
  - name: openpitrix-im-service
    protocol: TCP
    port: 9119
    targetPort: 9119
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-im-service-deployment
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-im-service
    version: ${IM_VERSION}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-im-service
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-im-service
        version: ${IM_VERSION}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.${NAMESPACE}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.${NAMESPACE}.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-im-service
        image: ${IM_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - im
        ports:
        - containerPort: 9119
          name: im-service
        env:
        - name: IM_LOG_LEVEL
          value: ${OPENPITRIX_LOG_LEVEL}
        - name: IM_DB_LOG_MODE_ENABLE
          value: "${DB_LOG_MODE_ENABLE}"
        - name: IM_DB_HOST
          value: "openpitrix-db"
        - name: IM_DB_DATABASE
          value: "im"
        - name: IM_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
