apiVersion: v1
kind: Service
metadata:
  name: openpitrix-notification
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-notification
    version: ${NOTIFICATION_VERSION}
spec:
  selector:
    app: openpitrix
    component: openpitrix-notification
  ports:
  - name:  openpitrix-notification
    protocol: TCP
    port: 9201
    targetPort: 9201
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-notification-deployment
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-notification
    version: ${NOTIFICATION_VERSION}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-notification
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-notification
        version: ${NOTIFICATION_VERSION}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.${NAMESPACE}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.${NAMESPACE}.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-notification
        image: ${NOTIFICATION_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - notification
        ports:
        - containerPort: 9201
          name: notification
        env:
        - name: NOTIFICATION_LOG_LEVEL
          value: ${OPENPITRIX_LOG_LEVEL}
        - name: NOTIFICATION_GRPC_SHOW_ERROR_CAUSE
          value: "${GRPC_SHOW_ERROR_CAUSE}"
        - name: NOTIFICATION_ETCD_ENDPOINTS
          value: "openpitrix-etcd:2379"
        - name: NOTIFICATION_MYSQL_HOST
          value: "openpitrix-db"
        - name: NOTIFICATION_MYSQL_DATABASE
          value: "notification"
        - name: NOTIFICATION_MYSQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
