// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"AppHub/src/api/swagger/models"
)

// PostV1ClustersNoContentCode is the HTTP code returned for type PostV1ClustersNoContent
const PostV1ClustersNoContentCode int = 204

/*PostV1ClustersNoContent Cluster succesfully created.

swagger:response postV1ClustersNoContent
*/
type PostV1ClustersNoContent struct {
}

// NewPostV1ClustersNoContent creates PostV1ClustersNoContent with default headers values
func NewPostV1ClustersNoContent() *PostV1ClustersNoContent {
	return &PostV1ClustersNoContent{}
}

// WriteResponse to the client
func (o *PostV1ClustersNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// PostV1ClustersBadRequestCode is the HTTP code returned for type PostV1ClustersBadRequest
const PostV1ClustersBadRequestCode int = 400

/*PostV1ClustersBadRequest Cluster couldn't have been created.

swagger:response postV1ClustersBadRequest
*/
type PostV1ClustersBadRequest struct {
}

// NewPostV1ClustersBadRequest creates PostV1ClustersBadRequest with default headers values
func NewPostV1ClustersBadRequest() *PostV1ClustersBadRequest {
	return &PostV1ClustersBadRequest{}
}

// WriteResponse to the client
func (o *PostV1ClustersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// PostV1ClustersInternalServerErrorCode is the HTTP code returned for type PostV1ClustersInternalServerError
const PostV1ClustersInternalServerErrorCode int = 500

/*PostV1ClustersInternalServerError An unexpected error occured.

swagger:response postV1ClustersInternalServerError
*/
type PostV1ClustersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostV1ClustersInternalServerError creates PostV1ClustersInternalServerError with default headers values
func NewPostV1ClustersInternalServerError() *PostV1ClustersInternalServerError {
	return &PostV1ClustersInternalServerError{}
}

// WithPayload adds the payload to the post v1 clusters internal server error response
func (o *PostV1ClustersInternalServerError) WithPayload(payload *models.Error) *PostV1ClustersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 clusters internal server error response
func (o *PostV1ClustersInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1ClustersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
