CREATE TABLE IF NOT EXISTS job (
	job_id      VARCHAR(50) NOT NULL,
	cluster_id  VARCHAR(50) NOT NULL,
	app_id      VARCHAR(50) NOT NULL,
	version_id  VARCHAR(50) NOT NULL,
	job_action  VARCHAR(50) NOT NULL,
	status      VARCHAR(50) NOT NULL,
	create_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status_time TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
	error_code  INT(11)     NOT NULL,
	owner       VARCHAR(50) NOT NULL,
	directive   TEXT        NOT NULL,
	executor    VARCHAR(50) NOT NULL,
	task_count  INT(11)     NOT NULL,
	provider    VARCHAR(50) NOT NULL,
	PRIMARY KEY (job_id),
	INDEX job_create_time_index (create_time ASC),
	INDEX job_job_action_index (job_action ASC),
	INDEX job_cluster_id_index (cluster_id ASC),
	INDEX job_owner_index (owner ASC),
	INDEX job_executor_index (executor ASC),
	INDEX job_provider_index (provider ASC),
	INDEX job_status_index (status ASC)
);
