apiVersion: v1
kind: Service
metadata:
  name: openpitrix-minio
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    tier: minio
    version: ${VERSION}
spec:
  selector:
    app: openpitrix
    tier: minio
  ports:
  - name: tcp
    protocol: TCP
    port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openpitrix-minio-pvc
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    tier: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-minio-deployment
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    tier: minio
    version: ${VERSION}
spec:
  selector:
    matchLabels:
      app: openpitrix
      tier: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openpitrix
        tier: minio
        version: ${VERSION}
    spec:
      containers:
      - name: openpitrix-minio
        image: minio/minio:RELEASE.2018-09-25T21-34-43Z
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command: ["sh", "-c", "mkdir -p /data/openpitrix-attachment /data/openpitrix-internal-repo/vmbased /data/openpitrix-internal-repo/helm ${REPO_DIR}"]
        args:
          - server
          - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: "openpitrixminioaccesskey"
        - name: MINIO_SECRET_KEY
          value: "openpitrixminiosecretkey"
        ports:
        - containerPort: 9000
          name: minio
        volumeMounts:
        - name: minio-persistent-storage
          mountPath: /data
      volumes:
      - name: minio-persistent-storage
        persistentVolumeClaim:
          claimName: openpitrix-minio-pvc
