// Code generated by go-swagger; DO NOT EDIT.

package app_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// BusinessAdminRejectAppVersionReader is a Reader for the BusinessAdminRejectAppVersion structure.
type BusinessAdminRejectAppVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BusinessAdminRejectAppVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBusinessAdminRejectAppVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBusinessAdminRejectAppVersionOK creates a BusinessAdminRejectAppVersionOK with default headers values
func NewBusinessAdminRejectAppVersionOK() *BusinessAdminRejectAppVersionOK {
	return &BusinessAdminRejectAppVersionOK{}
}

/*BusinessAdminRejectAppVersionOK handles this case with default header values.

A successful response.
*/
type BusinessAdminRejectAppVersionOK struct {
	Payload *models.OpenpitrixRejectAppVersionResponse
}

func (o *BusinessAdminRejectAppVersionOK) Error() string {
	return fmt.Sprintf("[POST /v1/app_version/action/business_admin/reject][%d] businessAdminRejectAppVersionOK  %+v", 200, o.Payload)
}

func (o *BusinessAdminRejectAppVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OpenpitrixRejectAppVersionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
