// Code generated by go-swagger; DO NOT EDIT.

package app_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDescribeAppVersionReviewsParams creates a new DescribeAppVersionReviewsParams object
// with the default values initialized.
func NewDescribeAppVersionReviewsParams() *DescribeAppVersionReviewsParams {
	var ()
	return &DescribeAppVersionReviewsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDescribeAppVersionReviewsParamsWithTimeout creates a new DescribeAppVersionReviewsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDescribeAppVersionReviewsParamsWithTimeout(timeout time.Duration) *DescribeAppVersionReviewsParams {
	var ()
	return &DescribeAppVersionReviewsParams{

		timeout: timeout,
	}
}

// NewDescribeAppVersionReviewsParamsWithContext creates a new DescribeAppVersionReviewsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDescribeAppVersionReviewsParamsWithContext(ctx context.Context) *DescribeAppVersionReviewsParams {
	var ()
	return &DescribeAppVersionReviewsParams{

		Context: ctx,
	}
}

// NewDescribeAppVersionReviewsParamsWithHTTPClient creates a new DescribeAppVersionReviewsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDescribeAppVersionReviewsParamsWithHTTPClient(client *http.Client) *DescribeAppVersionReviewsParams {
	var ()
	return &DescribeAppVersionReviewsParams{
		HTTPClient: client,
	}
}

/*DescribeAppVersionReviewsParams contains all the parameters to send to the API endpoint
for the describe app version reviews operation typically these are written to a http.Request
*/
type DescribeAppVersionReviewsParams struct {

	/*AppID
	  app ids.

	*/
	AppID []string
	/*DisplayColumns
	  select columns to display.

	*/
	DisplayColumns []string
	/*Limit
	  data limit per page, default is 20, max value is 200.

	*/
	Limit *int64
	/*Offset
	  data offset, default is 0.

	*/
	Offset *int64
	/*Reverse
	  value = 0 sort ASC, value = 1 sort DESC.

	*/
	Reverse *bool
	/*ReviewID
	  app version review ids.

	*/
	ReviewID []string
	/*Reviewer
	  reviewer of app version eg.[global_admin|developer|business|technical|isv].

	*/
	Reviewer []string
	/*SearchWord
	  query key, support these fields(review_id, version_id, app_id, status, reviewer, app_name, owner).

	*/
	SearchWord *string
	/*SortKey
	  sort key, order by sort_key, default create_time.

	*/
	SortKey *string
	/*Status
	  app version status eg.[isv-in-review|isv-passed|isv-rejected|isv-draft|business-in-review|business-passed|business-rejected|develop-draft|develop-in-review|develop-passed|develop-rejected|develop-draft].

	*/
	Status []string
	/*VersionID
	  app version ids.

	*/
	VersionID []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithTimeout(timeout time.Duration) *DescribeAppVersionReviewsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithContext(ctx context.Context) *DescribeAppVersionReviewsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithHTTPClient(client *http.Client) *DescribeAppVersionReviewsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithAppID(appID []string) *DescribeAppVersionReviewsParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetAppID(appID []string) {
	o.AppID = appID
}

// WithDisplayColumns adds the displayColumns to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithDisplayColumns(displayColumns []string) *DescribeAppVersionReviewsParams {
	o.SetDisplayColumns(displayColumns)
	return o
}

// SetDisplayColumns adds the displayColumns to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetDisplayColumns(displayColumns []string) {
	o.DisplayColumns = displayColumns
}

// WithLimit adds the limit to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithLimit(limit *int64) *DescribeAppVersionReviewsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithOffset(offset *int64) *DescribeAppVersionReviewsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithReverse adds the reverse to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithReverse(reverse *bool) *DescribeAppVersionReviewsParams {
	o.SetReverse(reverse)
	return o
}

// SetReverse adds the reverse to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetReverse(reverse *bool) {
	o.Reverse = reverse
}

// WithReviewID adds the reviewID to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithReviewID(reviewID []string) *DescribeAppVersionReviewsParams {
	o.SetReviewID(reviewID)
	return o
}

// SetReviewID adds the reviewId to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetReviewID(reviewID []string) {
	o.ReviewID = reviewID
}

// WithReviewer adds the reviewer to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithReviewer(reviewer []string) *DescribeAppVersionReviewsParams {
	o.SetReviewer(reviewer)
	return o
}

// SetReviewer adds the reviewer to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetReviewer(reviewer []string) {
	o.Reviewer = reviewer
}

// WithSearchWord adds the searchWord to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithSearchWord(searchWord *string) *DescribeAppVersionReviewsParams {
	o.SetSearchWord(searchWord)
	return o
}

// SetSearchWord adds the searchWord to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetSearchWord(searchWord *string) {
	o.SearchWord = searchWord
}

// WithSortKey adds the sortKey to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithSortKey(sortKey *string) *DescribeAppVersionReviewsParams {
	o.SetSortKey(sortKey)
	return o
}

// SetSortKey adds the sortKey to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetSortKey(sortKey *string) {
	o.SortKey = sortKey
}

// WithStatus adds the status to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithStatus(status []string) *DescribeAppVersionReviewsParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetStatus(status []string) {
	o.Status = status
}

// WithVersionID adds the versionID to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) WithVersionID(versionID []string) *DescribeAppVersionReviewsParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the describe app version reviews params
func (o *DescribeAppVersionReviewsParams) SetVersionID(versionID []string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *DescribeAppVersionReviewsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	valuesAppID := o.AppID

	joinedAppID := swag.JoinByFormat(valuesAppID, "multi")
	// query array param app_id
	if err := r.SetQueryParam("app_id", joinedAppID...); err != nil {
		return err
	}

	valuesDisplayColumns := o.DisplayColumns

	joinedDisplayColumns := swag.JoinByFormat(valuesDisplayColumns, "multi")
	// query array param display_columns
	if err := r.SetQueryParam("display_columns", joinedDisplayColumns...); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Reverse != nil {

		// query param reverse
		var qrReverse bool
		if o.Reverse != nil {
			qrReverse = *o.Reverse
		}
		qReverse := swag.FormatBool(qrReverse)
		if qReverse != "" {
			if err := r.SetQueryParam("reverse", qReverse); err != nil {
				return err
			}
		}

	}

	valuesReviewID := o.ReviewID

	joinedReviewID := swag.JoinByFormat(valuesReviewID, "multi")
	// query array param review_id
	if err := r.SetQueryParam("review_id", joinedReviewID...); err != nil {
		return err
	}

	valuesReviewer := o.Reviewer

	joinedReviewer := swag.JoinByFormat(valuesReviewer, "multi")
	// query array param reviewer
	if err := r.SetQueryParam("reviewer", joinedReviewer...); err != nil {
		return err
	}

	if o.SearchWord != nil {

		// query param search_word
		var qrSearchWord string
		if o.SearchWord != nil {
			qrSearchWord = *o.SearchWord
		}
		qSearchWord := qrSearchWord
		if qSearchWord != "" {
			if err := r.SetQueryParam("search_word", qSearchWord); err != nil {
				return err
			}
		}

	}

	if o.SortKey != nil {

		// query param sort_key
		var qrSortKey string
		if o.SortKey != nil {
			qrSortKey = *o.SortKey
		}
		qSortKey := qrSortKey
		if qSortKey != "" {
			if err := r.SetQueryParam("sort_key", qSortKey); err != nil {
				return err
			}
		}

	}

	valuesStatus := o.Status

	joinedStatus := swag.JoinByFormat(valuesStatus, "multi")
	// query array param status
	if err := r.SetQueryParam("status", joinedStatus...); err != nil {
		return err
	}

	valuesVersionID := o.VersionID

	joinedVersionID := swag.JoinByFormat(valuesVersionID, "multi")
	// query array param version_id
	if err := r.SetQueryParam("version_id", joinedVersionID...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
