// Code generated by go-swagger; DO NOT EDIT.

package app_manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"openpitrix.io/openpitrix/test/models"
)

// NewRecoverAppVersionParams creates a new RecoverAppVersionParams object
// with the default values initialized.
func NewRecoverAppVersionParams() *RecoverAppVersionParams {
	var ()
	return &RecoverAppVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRecoverAppVersionParamsWithTimeout creates a new RecoverAppVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRecoverAppVersionParamsWithTimeout(timeout time.Duration) *RecoverAppVersionParams {
	var ()
	return &RecoverAppVersionParams{

		timeout: timeout,
	}
}

// NewRecoverAppVersionParamsWithContext creates a new RecoverAppVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewRecoverAppVersionParamsWithContext(ctx context.Context) *RecoverAppVersionParams {
	var ()
	return &RecoverAppVersionParams{

		Context: ctx,
	}
}

// NewRecoverAppVersionParamsWithHTTPClient creates a new RecoverAppVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRecoverAppVersionParamsWithHTTPClient(client *http.Client) *RecoverAppVersionParams {
	var ()
	return &RecoverAppVersionParams{
		HTTPClient: client,
	}
}

/*RecoverAppVersionParams contains all the parameters to send to the API endpoint
for the recover app version operation typically these are written to a http.Request
*/
type RecoverAppVersionParams struct {

	/*Body*/
	Body *models.OpenpitrixRecoverAppVersionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the recover app version params
func (o *RecoverAppVersionParams) WithTimeout(timeout time.Duration) *RecoverAppVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the recover app version params
func (o *RecoverAppVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the recover app version params
func (o *RecoverAppVersionParams) WithContext(ctx context.Context) *RecoverAppVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the recover app version params
func (o *RecoverAppVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the recover app version params
func (o *RecoverAppVersionParams) WithHTTPClient(client *http.Client) *RecoverAppVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the recover app version params
func (o *RecoverAppVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the recover app version params
func (o *RecoverAppVersionParams) WithBody(body *models.OpenpitrixRecoverAppVersionRequest) *RecoverAppVersionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the recover app version params
func (o *RecoverAppVersionParams) SetBody(body *models.OpenpitrixRecoverAppVersionRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RecoverAppVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
