# Copyright 2017 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

# type App struct {
#   appId       string     `required pattern="app-[a-zA-Z0-9]{11}", minLength=12, maxLength=12`
#   name        *string    `optional`
#   description *string    `optional`
#   createTime  *time.Time `optional`
# }

required:
  - appId

properties:
  name:
    type: string
  description:
    type: string
  url:
    type: string
  appId:
    type: string
    pattern: 'app-[a-zA-Z0-9]{8}'
    minLength: 12
    maxLength: 12
  createTime:
    type: string
    format: date-time
    readOnly: true
    example: 2017-09-17T12:36:58.014Z
