// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateJobRequest struct {
	ClusterId            *wrappers.StringValue `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	AppId                *wrappers.StringValue `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	VersionId            *wrappers.StringValue `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	JobAction            *wrappers.StringValue `protobuf:"bytes,4,opt,name=job_action,json=jobAction,proto3" json:"job_action,omitempty"`
	Provider             *wrappers.StringValue `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Directive            *wrappers.StringValue `protobuf:"bytes,6,opt,name=directive,proto3" json:"directive,omitempty"`
	RuntimeId            *wrappers.StringValue `protobuf:"bytes,7,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetClusterId() *wrappers.StringValue {
	if m != nil {
		return m.ClusterId
	}
	return nil
}

func (m *CreateJobRequest) GetAppId() *wrappers.StringValue {
	if m != nil {
		return m.AppId
	}
	return nil
}

func (m *CreateJobRequest) GetVersionId() *wrappers.StringValue {
	if m != nil {
		return m.VersionId
	}
	return nil
}

func (m *CreateJobRequest) GetJobAction() *wrappers.StringValue {
	if m != nil {
		return m.JobAction
	}
	return nil
}

func (m *CreateJobRequest) GetProvider() *wrappers.StringValue {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *CreateJobRequest) GetDirective() *wrappers.StringValue {
	if m != nil {
		return m.Directive
	}
	return nil
}

func (m *CreateJobRequest) GetRuntimeId() *wrappers.StringValue {
	if m != nil {
		return m.RuntimeId
	}
	return nil
}

type CreateJobResponse struct {
	JobId                *wrappers.StringValue `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ClusterId            *wrappers.StringValue `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	AppId                *wrappers.StringValue `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	VersionId            *wrappers.StringValue `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	RuntimeId            *wrappers.StringValue `protobuf:"bytes,5,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetJobId() *wrappers.StringValue {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *CreateJobResponse) GetClusterId() *wrappers.StringValue {
	if m != nil {
		return m.ClusterId
	}
	return nil
}

func (m *CreateJobResponse) GetAppId() *wrappers.StringValue {
	if m != nil {
		return m.AppId
	}
	return nil
}

func (m *CreateJobResponse) GetVersionId() *wrappers.StringValue {
	if m != nil {
		return m.VersionId
	}
	return nil
}

func (m *CreateJobResponse) GetRuntimeId() *wrappers.StringValue {
	if m != nil {
		return m.RuntimeId
	}
	return nil
}

type Job struct {
	JobId                *wrappers.StringValue `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ClusterId            *wrappers.StringValue `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	AppId                *wrappers.StringValue `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	VersionId            *wrappers.StringValue `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	JobAction            *wrappers.StringValue `protobuf:"bytes,5,opt,name=job_action,json=jobAction,proto3" json:"job_action,omitempty"`
	Status               *wrappers.StringValue `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode            *wrappers.UInt32Value `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Directive            *wrappers.StringValue `protobuf:"bytes,8,opt,name=directive,proto3" json:"directive,omitempty"`
	Executor             *wrappers.StringValue `protobuf:"bytes,9,opt,name=executor,proto3" json:"executor,omitempty"`
	TaskCount            *wrappers.UInt32Value `protobuf:"bytes,10,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	OwnerPath            *wrappers.StringValue `protobuf:"bytes,11,opt,name=owner_path,json=ownerPath,proto3" json:"owner_path,omitempty"`
	Provider             *wrappers.StringValue `protobuf:"bytes,12,opt,name=provider,proto3" json:"provider,omitempty"`
	RuntimeId            *wrappers.StringValue `protobuf:"bytes,13,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	CreateTime           *timestamp.Timestamp  `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	StatusTime           *timestamp.Timestamp  `protobuf:"bytes,15,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetJobId() *wrappers.StringValue {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *Job) GetClusterId() *wrappers.StringValue {
	if m != nil {
		return m.ClusterId
	}
	return nil
}

func (m *Job) GetAppId() *wrappers.StringValue {
	if m != nil {
		return m.AppId
	}
	return nil
}

func (m *Job) GetVersionId() *wrappers.StringValue {
	if m != nil {
		return m.VersionId
	}
	return nil
}

func (m *Job) GetJobAction() *wrappers.StringValue {
	if m != nil {
		return m.JobAction
	}
	return nil
}

func (m *Job) GetStatus() *wrappers.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Job) GetErrorCode() *wrappers.UInt32Value {
	if m != nil {
		return m.ErrorCode
	}
	return nil
}

func (m *Job) GetDirective() *wrappers.StringValue {
	if m != nil {
		return m.Directive
	}
	return nil
}

func (m *Job) GetExecutor() *wrappers.StringValue {
	if m != nil {
		return m.Executor
	}
	return nil
}

func (m *Job) GetTaskCount() *wrappers.UInt32Value {
	if m != nil {
		return m.TaskCount
	}
	return nil
}

func (m *Job) GetOwnerPath() *wrappers.StringValue {
	if m != nil {
		return m.OwnerPath
	}
	return nil
}

func (m *Job) GetProvider() *wrappers.StringValue {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *Job) GetRuntimeId() *wrappers.StringValue {
	if m != nil {
		return m.RuntimeId
	}
	return nil
}

func (m *Job) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Job) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type DescribeJobsRequest struct {
	SearchWord *wrappers.StringValue `protobuf:"bytes,1,opt,name=search_word,json=searchWord,proto3" json:"search_word,omitempty"`
	SortKey    *wrappers.StringValue `protobuf:"bytes,2,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
	Reverse    *wrappers.BoolValue   `protobuf:"bytes,3,opt,name=reverse,proto3" json:"reverse,omitempty"`
	// default is 20, max value is 200
	Limit uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// default is 0
	Offset               uint32                `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	DisplayColumns       []string              `protobuf:"bytes,6,rep,name=display_columns,json=displayColumns,proto3" json:"display_columns,omitempty"`
	JobId                []string              `protobuf:"bytes,11,rep,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ClusterId            *wrappers.StringValue `protobuf:"bytes,12,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	AppId                *wrappers.StringValue `protobuf:"bytes,13,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	VersionId            *wrappers.StringValue `protobuf:"bytes,14,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Executor             *wrappers.StringValue `protobuf:"bytes,15,opt,name=executor,proto3" json:"executor,omitempty"`
	Provider             *wrappers.StringValue `protobuf:"bytes,16,opt,name=provider,proto3" json:"provider,omitempty"`
	RuntimeId            *wrappers.StringValue `protobuf:"bytes,17,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Status               []string              `protobuf:"bytes,18,rep,name=status,proto3" json:"status,omitempty"`
	OwnerPath            []string              `protobuf:"bytes,19,rep,name=owner_path,json=ownerPath,proto3" json:"owner_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DescribeJobsRequest) Reset()         { *m = DescribeJobsRequest{} }
func (m *DescribeJobsRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeJobsRequest) ProtoMessage()    {}
func (*DescribeJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{3}
}

func (m *DescribeJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeJobsRequest.Unmarshal(m, b)
}
func (m *DescribeJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeJobsRequest.Marshal(b, m, deterministic)
}
func (m *DescribeJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeJobsRequest.Merge(m, src)
}
func (m *DescribeJobsRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeJobsRequest.Size(m)
}
func (m *DescribeJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeJobsRequest proto.InternalMessageInfo

func (m *DescribeJobsRequest) GetSearchWord() *wrappers.StringValue {
	if m != nil {
		return m.SearchWord
	}
	return nil
}

func (m *DescribeJobsRequest) GetSortKey() *wrappers.StringValue {
	if m != nil {
		return m.SortKey
	}
	return nil
}

func (m *DescribeJobsRequest) GetReverse() *wrappers.BoolValue {
	if m != nil {
		return m.Reverse
	}
	return nil
}

func (m *DescribeJobsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeJobsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeJobsRequest) GetDisplayColumns() []string {
	if m != nil {
		return m.DisplayColumns
	}
	return nil
}

func (m *DescribeJobsRequest) GetJobId() []string {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *DescribeJobsRequest) GetClusterId() *wrappers.StringValue {
	if m != nil {
		return m.ClusterId
	}
	return nil
}

func (m *DescribeJobsRequest) GetAppId() *wrappers.StringValue {
	if m != nil {
		return m.AppId
	}
	return nil
}

func (m *DescribeJobsRequest) GetVersionId() *wrappers.StringValue {
	if m != nil {
		return m.VersionId
	}
	return nil
}

func (m *DescribeJobsRequest) GetExecutor() *wrappers.StringValue {
	if m != nil {
		return m.Executor
	}
	return nil
}

func (m *DescribeJobsRequest) GetProvider() *wrappers.StringValue {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *DescribeJobsRequest) GetRuntimeId() *wrappers.StringValue {
	if m != nil {
		return m.RuntimeId
	}
	return nil
}

func (m *DescribeJobsRequest) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeJobsRequest) GetOwnerPath() []string {
	if m != nil {
		return m.OwnerPath
	}
	return nil
}

type DescribeJobsResponse struct {
	TotalCount           uint32   `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	JobSet               []*Job   `protobuf:"bytes,2,rep,name=job_set,json=jobSet,proto3" json:"job_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeJobsResponse) Reset()         { *m = DescribeJobsResponse{} }
func (m *DescribeJobsResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeJobsResponse) ProtoMessage()    {}
func (*DescribeJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{4}
}

func (m *DescribeJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeJobsResponse.Unmarshal(m, b)
}
func (m *DescribeJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeJobsResponse.Marshal(b, m, deterministic)
}
func (m *DescribeJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeJobsResponse.Merge(m, src)
}
func (m *DescribeJobsResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeJobsResponse.Size(m)
}
func (m *DescribeJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeJobsResponse proto.InternalMessageInfo

func (m *DescribeJobsResponse) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *DescribeJobsResponse) GetJobSet() []*Job {
	if m != nil {
		return m.JobSet
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateJobRequest)(nil), "openpitrix.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "openpitrix.CreateJobResponse")
	proto.RegisterType((*Job)(nil), "openpitrix.Job")
	proto.RegisterType((*DescribeJobsRequest)(nil), "openpitrix.DescribeJobsRequest")
	proto.RegisterType((*DescribeJobsResponse)(nil), "openpitrix.DescribeJobsResponse")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 827 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0x96, 0xed, 0xd8, 0xb1, 0xcb, 0xf9, 0xd9, 0xed, 0x5d, 0x56, 0x83, 0xc9, 0x12, 0xcb, 0x17,
	0x72, 0x60, 0x6d, 0x91, 0xac, 0xc4, 0x8a, 0x15, 0x87, 0xdd, 0x70, 0x20, 0x41, 0x48, 0xc8, 0xcb,
	0x8f, 0xc4, 0x65, 0xd4, 0x33, 0x53, 0x71, 0xda, 0x3b, 0x99, 0x6a, 0xba, 0x7b, 0xe2, 0xcd, 0x11,
	0x1e, 0x01, 0x9e, 0x04, 0x89, 0x87, 0xe0, 0xce, 0x8d, 0x33, 0x4f, 0xc1, 0x09, 0x75, 0x4f, 0xdb,
	0x3b, 0xde, 0x6c, 0xc4, 0x4c, 0x38, 0x72, 0xb2, 0xa6, 0xeb, 0xfb, 0x5c, 0x35, 0x55, 0xf5, 0x7d,
	0x3d, 0xd0, 0x9b, 0x53, 0x34, 0x96, 0x8a, 0x0c, 0x31, 0x20, 0x89, 0x99, 0x14, 0x46, 0x89, 0x57,
	0x83, 0xf7, 0x67, 0x44, 0xb3, 0x14, 0x27, 0x2e, 0x12, 0xe5, 0x67, 0x93, 0x85, 0xe2, 0x52, 0xa2,
	0xd2, 0x05, 0x76, 0xb0, 0xff, 0x66, 0xdc, 0x88, 0x0b, 0xd4, 0x86, 0x5f, 0x48, 0x0f, 0xd8, 0xf3,
	0x00, 0x2e, 0xc5, 0x84, 0x67, 0x19, 0x19, 0x6e, 0x04, 0x65, 0x4b, 0xfa, 0x87, 0xee, 0x27, 0x7e,
	0x34, 0xc3, 0xec, 0x91, 0x5e, 0xf0, 0xd9, 0x0c, 0xd5, 0x84, 0xa4, 0x43, 0x5c, 0x47, 0x8f, 0x7e,
	0x6d, 0xc1, 0x9d, 0x63, 0x85, 0xdc, 0xe0, 0x29, 0x45, 0x53, 0xfc, 0x21, 0x47, 0x6d, 0xd8, 0x53,
	0x80, 0x38, 0xcd, 0xb5, 0x41, 0x15, 0x8a, 0x24, 0x68, 0x0c, 0x1b, 0x07, 0xfd, 0xc3, 0xbd, 0x71,
	0x91, 0x75, 0xbc, 0x2c, 0x6b, 0xfc, 0xc2, 0x28, 0x91, 0xcd, 0xbe, 0xe5, 0x69, 0x8e, 0xd3, 0x9e,
	0xc7, 0x9f, 0x24, 0xec, 0x08, 0x3a, 0x5c, 0x4a, 0x4b, 0x6c, 0x56, 0x20, 0xb6, 0xb9, 0x94, 0x27,
	0x89, 0xcd, 0x78, 0x89, 0x4a, 0x0b, 0xca, 0x2c, 0xb1, 0x55, 0x25, 0xa3, 0xc7, 0x17, 0xe4, 0x39,
	0x45, 0x21, 0x8f, 0xed, 0x8b, 0x05, 0x1b, 0x55, 0xc8, 0x73, 0x8a, 0x9e, 0x39, 0x38, 0x7b, 0x02,
	0x5d, 0xa9, 0xe8, 0x52, 0x24, 0xa8, 0x82, 0x76, 0x05, 0xea, 0x0a, 0xcd, 0x3e, 0x81, 0x5e, 0x22,
	0x14, 0xc6, 0x46, 0x5c, 0x62, 0xd0, 0xa9, 0x92, 0x75, 0x05, 0xb7, 0x25, 0xab, 0x3c, 0xb3, 0x83,
	0xb5, 0xef, 0xbb, 0x59, 0x85, 0xec, 0xf1, 0x27, 0xc9, 0xe8, 0xb7, 0x26, 0xdc, 0x2d, 0xcd, 0x4c,
	0x4b, 0xca, 0x34, 0xda, 0xbe, 0xdb, 0x2e, 0x54, 0x1c, 0x58, 0x7b, 0x4e, 0x51, 0xd1, 0xba, 0xd2,
	0xa4, 0x9b, 0xb7, 0x9d, 0x74, 0xeb, 0xb6, 0x93, 0xde, 0xa8, 0x3d, 0xe9, 0x52, 0xdb, 0xda, 0xf5,
	0xda, 0xf6, 0x77, 0x07, 0x5a, 0xa7, 0x14, 0xfd, 0x5f, 0x1a, 0x55, 0x92, 0x44, 0xbb, 0x9e, 0x24,
	0x1e, 0x43, 0x47, 0x1b, 0x6e, 0x72, 0x5d, 0x69, 0xab, 0x3d, 0xd6, 0xa6, 0x44, 0xa5, 0x48, 0x85,
	0x31, 0x25, 0x78, 0xe3, 0x4a, 0x7f, 0x73, 0x92, 0x99, 0xa3, 0x43, 0x9f, 0xd2, 0xe1, 0x8f, 0x29,
	0xc1, 0x75, 0x2d, 0x75, 0xeb, 0x69, 0xe9, 0x09, 0x74, 0xf1, 0x15, 0xc6, 0xb9, 0x21, 0x15, 0xf4,
	0xaa, 0x28, 0x78, 0x89, 0xb6, 0x25, 0x1b, 0xae, 0x5f, 0x86, 0x31, 0xe5, 0x99, 0x09, 0xa0, 0x4a,
	0xc9, 0x16, 0x7f, 0x6c, 0xe1, 0x96, 0x4c, 0x8b, 0x0c, 0x55, 0x28, 0xb9, 0x39, 0x0f, 0xfa, 0x55,
	0x6a, 0x76, 0xf8, 0xaf, 0xb8, 0x39, 0x5f, 0x73, 0x9d, 0xad, 0x5a, 0xae, 0xb3, 0x2e, 0x81, 0xed,
	0x5a, 0x12, 0x60, 0x4f, 0xa1, 0x1f, 0x3b, 0xe3, 0x08, 0xed, 0x41, 0xb0, 0xe3, 0xd8, 0x83, 0x6b,
	0xec, 0xaf, 0x97, 0x17, 0xce, 0x14, 0x0a, 0xb8, 0x3d, 0xb0, 0xe4, 0x62, 0xd4, 0x05, 0x79, 0xf7,
	0xdf, 0xc9, 0x05, 0xdc, 0x1e, 0x8c, 0x7e, 0x6f, 0xc3, 0xbd, 0xcf, 0x50, 0xc7, 0x4a, 0x44, 0xd6,
	0xb5, 0xf4, 0xf2, 0xaa, 0xf9, 0x14, 0xfa, 0x1a, 0xb9, 0x8a, 0xcf, 0xc3, 0x05, 0xa9, 0x6a, 0x8a,
	0x84, 0x82, 0xf0, 0x1d, 0xa9, 0x84, 0x7d, 0x0c, 0x5d, 0x4d, 0xca, 0x84, 0x2f, 0xf1, 0xaa, 0x92,
	0x28, 0x37, 0x2d, 0xfa, 0x0b, 0xbc, 0x62, 0x8f, 0x61, 0x53, 0xa1, 0xd5, 0x0b, 0x7a, 0x4d, 0x5e,
	0x7f, 0x91, 0xe7, 0x44, 0xa9, 0x67, 0x79, 0x28, 0xbb, 0x0f, 0xed, 0x54, 0x5c, 0x08, 0xe3, 0xe4,
	0xb8, 0x3d, 0x2d, 0x1e, 0xd8, 0x03, 0xe8, 0xd0, 0xd9, 0x99, 0x46, 0xe3, 0x84, 0xb6, 0x3d, 0xf5,
	0x4f, 0xec, 0x03, 0xd8, 0x4d, 0x84, 0x96, 0x29, 0xbf, 0x0a, 0x63, 0x4a, 0xf3, 0x8b, 0xcc, 0x0a,
	0xaa, 0x75, 0xd0, 0x9b, 0xee, 0xf8, 0xe3, 0xe3, 0xe2, 0x94, 0xbd, 0xb3, 0x72, 0xa4, 0xbe, 0x8b,
	0xbf, 0xd5, 0x73, 0xb6, 0x6e, 0xeb, 0x39, 0xdb, 0xb7, 0xf5, 0x9c, 0x9d, 0x7a, 0x9e, 0x53, 0xd6,
	0xe1, 0x6e, 0x2d, 0x1d, 0x96, 0xd5, 0x70, 0xe7, 0x3f, 0xa8, 0xe1, 0x6e, 0x3d, 0x35, 0x3c, 0x58,
	0xf9, 0x1c, 0x73, 0x6d, 0x5f, 0x3a, 0xd9, 0xc3, 0x35, 0x65, 0xdf, 0x73, 0xb1, 0xd7, 0xda, 0x1d,
	0x71, 0xb8, 0xbf, 0xbe, 0xc9, 0xfe, 0x02, 0xde, 0x87, 0xbe, 0x21, 0xc3, 0x53, 0x6f, 0x27, 0x0d,
	0xb7, 0x0b, 0xe0, 0x8e, 0x0a, 0xc7, 0x38, 0x80, 0x4d, 0x3b, 0x66, 0xbb, 0x28, 0xcd, 0x61, 0xeb,
	0xa0, 0x7f, 0xb8, 0x3b, 0x7e, 0xfd, 0x59, 0x38, 0xb6, 0x77, 0xb9, 0x5d, 0x83, 0x17, 0x68, 0x0e,
	0xff, 0x6c, 0x00, 0x9c, 0x52, 0xf4, 0x25, 0xcf, 0xf8, 0x0c, 0x15, 0xfb, 0x1c, 0x7a, 0xab, 0xfb,
	0x9e, 0xed, 0x95, 0x49, 0x6f, 0x7e, 0xba, 0x0d, 0x1e, 0xde, 0x10, 0xf5, 0x35, 0xfe, 0xd8, 0x80,
	0xad, 0x72, 0xf1, 0x6c, 0xbf, 0x8c, 0x7f, 0x8b, 0x40, 0x07, 0xc3, 0x9b, 0x01, 0xc5, 0x7f, 0x8e,
	0xc6, 0x3f, 0x3f, 0x7b, 0x8f, 0xbd, 0x9b, 0xf8, 0xd0, 0x70, 0x4e, 0x91, 0x1e, 0x2e, 0x84, 0x39,
	0x1f, 0x9e, 0x89, 0xd4, 0xa0, 0xfa, 0xe9, 0x8f, 0xbf, 0x7e, 0x69, 0x02, 0xeb, 0x4e, 0x2e, 0x3f,
	0x9a, 0xd8, 0xd8, 0xf3, 0x8d, 0xef, 0x9b, 0x32, 0x8a, 0x3a, 0x6e, 0x3a, 0x47, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x41, 0x85, 0x3c, 0x68, 0x25, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobManagerClient is the client API for JobManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobManagerClient interface {
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	DescribeJobs(ctx context.Context, in *DescribeJobsRequest, opts ...grpc.CallOption) (*DescribeJobsResponse, error)
}

type jobManagerClient struct {
	cc *grpc.ClientConn
}

func NewJobManagerClient(cc *grpc.ClientConn) JobManagerClient {
	return &jobManagerClient{cc}
}

func (c *jobManagerClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.JobManager/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobManagerClient) DescribeJobs(ctx context.Context, in *DescribeJobsRequest, opts ...grpc.CallOption) (*DescribeJobsResponse, error) {
	out := new(DescribeJobsResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.JobManager/DescribeJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobManagerServer is the server API for JobManager service.
type JobManagerServer interface {
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	DescribeJobs(context.Context, *DescribeJobsRequest) (*DescribeJobsResponse, error)
}

func RegisterJobManagerServer(s *grpc.Server, srv JobManagerServer) {
	s.RegisterService(&_JobManager_serviceDesc, srv)
}

func _JobManager_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobManagerServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.JobManager/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobManagerServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobManager_DescribeJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobManagerServer).DescribeJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.JobManager/DescribeJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobManagerServer).DescribeJobs(ctx, req.(*DescribeJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openpitrix.JobManager",
	HandlerType: (*JobManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _JobManager_CreateJob_Handler,
		},
		{
			MethodName: "DescribeJobs",
			Handler:    _JobManager_DescribeJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}
