// Code generated by protoc-gen-go. DO NOT EDIT.
// source: market.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Market struct {
	MarketId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Visibility           *wrappers.StringValue `protobuf:"bytes,3,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Status               *wrappers.StringValue `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime           *timestamp.Timestamp  `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	StatusTime           *timestamp.Timestamp  `protobuf:"bytes,8,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{0}
}

func (m *Market) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Market.Unmarshal(m, b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Market.Marshal(b, m, deterministic)
}
func (m *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(m, src)
}
func (m *Market) XXX_Size() int {
	return xxx_messageInfo_Market.Size(m)
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetMarketId() *wrappers.StringValue {
	if m != nil {
		return m.MarketId
	}
	return nil
}

func (m *Market) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Market) GetVisibility() *wrappers.StringValue {
	if m != nil {
		return m.Visibility
	}
	return nil
}

func (m *Market) GetStatus() *wrappers.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Market) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Market) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Market) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Market) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type CreateMarketRequest struct {
	Name                 *wrappers.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Visibility           *wrappers.StringValue `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateMarketRequest) Reset()         { *m = CreateMarketRequest{} }
func (m *CreateMarketRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMarketRequest) ProtoMessage()    {}
func (*CreateMarketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{1}
}

func (m *CreateMarketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMarketRequest.Unmarshal(m, b)
}
func (m *CreateMarketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMarketRequest.Marshal(b, m, deterministic)
}
func (m *CreateMarketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMarketRequest.Merge(m, src)
}
func (m *CreateMarketRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMarketRequest.Size(m)
}
func (m *CreateMarketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMarketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMarketRequest proto.InternalMessageInfo

func (m *CreateMarketRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *CreateMarketRequest) GetVisibility() *wrappers.StringValue {
	if m != nil {
		return m.Visibility
	}
	return nil
}

func (m *CreateMarketRequest) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

type CreateMarketResponse struct {
	MarketId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateMarketResponse) Reset()         { *m = CreateMarketResponse{} }
func (m *CreateMarketResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMarketResponse) ProtoMessage()    {}
func (*CreateMarketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{2}
}

func (m *CreateMarketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMarketResponse.Unmarshal(m, b)
}
func (m *CreateMarketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMarketResponse.Marshal(b, m, deterministic)
}
func (m *CreateMarketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMarketResponse.Merge(m, src)
}
func (m *CreateMarketResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMarketResponse.Size(m)
}
func (m *CreateMarketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMarketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMarketResponse proto.InternalMessageInfo

func (m *CreateMarketResponse) GetMarketId() *wrappers.StringValue {
	if m != nil {
		return m.MarketId
	}
	return nil
}

type DescribeMarketsRequest struct {
	SearchWord           *wrappers.StringValue `protobuf:"bytes,1,opt,name=search_word,json=searchWord,proto3" json:"search_word,omitempty"`
	Limit                uint32                `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32                `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	SortKey              *wrappers.StringValue `protobuf:"bytes,4,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
	Reverse              *wrappers.BoolValue   `protobuf:"bytes,5,opt,name=reverse,proto3" json:"reverse,omitempty"`
	MarketId             []string              `protobuf:"bytes,11,rep,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Visibility           []string              `protobuf:"bytes,12,rep,name=visibility,proto3" json:"visibility,omitempty"`
	Status               []string              `protobuf:"bytes,13,rep,name=status,proto3" json:"status,omitempty"`
	Owner                []string              `protobuf:"bytes,14,rep,name=owner,proto3" json:"owner,omitempty"`
	UserId               []string              `protobuf:"bytes,15,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DescribeMarketsRequest) Reset()         { *m = DescribeMarketsRequest{} }
func (m *DescribeMarketsRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeMarketsRequest) ProtoMessage()    {}
func (*DescribeMarketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{3}
}

func (m *DescribeMarketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeMarketsRequest.Unmarshal(m, b)
}
func (m *DescribeMarketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeMarketsRequest.Marshal(b, m, deterministic)
}
func (m *DescribeMarketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeMarketsRequest.Merge(m, src)
}
func (m *DescribeMarketsRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeMarketsRequest.Size(m)
}
func (m *DescribeMarketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeMarketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeMarketsRequest proto.InternalMessageInfo

func (m *DescribeMarketsRequest) GetSearchWord() *wrappers.StringValue {
	if m != nil {
		return m.SearchWord
	}
	return nil
}

func (m *DescribeMarketsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeMarketsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeMarketsRequest) GetSortKey() *wrappers.StringValue {
	if m != nil {
		return m.SortKey
	}
	return nil
}

func (m *DescribeMarketsRequest) GetReverse() *wrappers.BoolValue {
	if m != nil {
		return m.Reverse
	}
	return nil
}

func (m *DescribeMarketsRequest) GetMarketId() []string {
	if m != nil {
		return m.MarketId
	}
	return nil
}

func (m *DescribeMarketsRequest) GetVisibility() []string {
	if m != nil {
		return m.Visibility
	}
	return nil
}

func (m *DescribeMarketsRequest) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeMarketsRequest) GetOwner() []string {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *DescribeMarketsRequest) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

type DescribeMarketsResponse struct {
	TotalCount           uint32    `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	MarketSet            []*Market `protobuf:"bytes,2,rep,name=market_set,json=marketSet,proto3" json:"market_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DescribeMarketsResponse) Reset()         { *m = DescribeMarketsResponse{} }
func (m *DescribeMarketsResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeMarketsResponse) ProtoMessage()    {}
func (*DescribeMarketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{4}
}

func (m *DescribeMarketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeMarketsResponse.Unmarshal(m, b)
}
func (m *DescribeMarketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeMarketsResponse.Marshal(b, m, deterministic)
}
func (m *DescribeMarketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeMarketsResponse.Merge(m, src)
}
func (m *DescribeMarketsResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeMarketsResponse.Size(m)
}
func (m *DescribeMarketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeMarketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeMarketsResponse proto.InternalMessageInfo

func (m *DescribeMarketsResponse) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *DescribeMarketsResponse) GetMarketSet() []*Market {
	if m != nil {
		return m.MarketSet
	}
	return nil
}

type ModifyMarketRequest struct {
	MarketId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Visibility           *wrappers.StringValue `protobuf:"bytes,3,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Status               *wrappers.StringValue `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModifyMarketRequest) Reset()         { *m = ModifyMarketRequest{} }
func (m *ModifyMarketRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyMarketRequest) ProtoMessage()    {}
func (*ModifyMarketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{5}
}

func (m *ModifyMarketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyMarketRequest.Unmarshal(m, b)
}
func (m *ModifyMarketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyMarketRequest.Marshal(b, m, deterministic)
}
func (m *ModifyMarketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyMarketRequest.Merge(m, src)
}
func (m *ModifyMarketRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyMarketRequest.Size(m)
}
func (m *ModifyMarketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyMarketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyMarketRequest proto.InternalMessageInfo

func (m *ModifyMarketRequest) GetMarketId() *wrappers.StringValue {
	if m != nil {
		return m.MarketId
	}
	return nil
}

func (m *ModifyMarketRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ModifyMarketRequest) GetVisibility() *wrappers.StringValue {
	if m != nil {
		return m.Visibility
	}
	return nil
}

func (m *ModifyMarketRequest) GetStatus() *wrappers.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ModifyMarketRequest) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

type ModifyMarketResponse struct {
	MarketId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModifyMarketResponse) Reset()         { *m = ModifyMarketResponse{} }
func (m *ModifyMarketResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyMarketResponse) ProtoMessage()    {}
func (*ModifyMarketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{6}
}

func (m *ModifyMarketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyMarketResponse.Unmarshal(m, b)
}
func (m *ModifyMarketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyMarketResponse.Marshal(b, m, deterministic)
}
func (m *ModifyMarketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyMarketResponse.Merge(m, src)
}
func (m *ModifyMarketResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyMarketResponse.Size(m)
}
func (m *ModifyMarketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyMarketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyMarketResponse proto.InternalMessageInfo

func (m *ModifyMarketResponse) GetMarketId() *wrappers.StringValue {
	if m != nil {
		return m.MarketId
	}
	return nil
}

type DeleteMarketsRequest struct {
	MarketId             []string `protobuf:"bytes,1,rep,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMarketsRequest) Reset()         { *m = DeleteMarketsRequest{} }
func (m *DeleteMarketsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMarketsRequest) ProtoMessage()    {}
func (*DeleteMarketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{7}
}

func (m *DeleteMarketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMarketsRequest.Unmarshal(m, b)
}
func (m *DeleteMarketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMarketsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMarketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMarketsRequest.Merge(m, src)
}
func (m *DeleteMarketsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMarketsRequest.Size(m)
}
func (m *DeleteMarketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMarketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMarketsRequest proto.InternalMessageInfo

func (m *DeleteMarketsRequest) GetMarketId() []string {
	if m != nil {
		return m.MarketId
	}
	return nil
}

type DeleteMarketsResponse struct {
	MarketId             []string `protobuf:"bytes,1,rep,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMarketsResponse) Reset()         { *m = DeleteMarketsResponse{} }
func (m *DeleteMarketsResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteMarketsResponse) ProtoMessage()    {}
func (*DeleteMarketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{8}
}

func (m *DeleteMarketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMarketsResponse.Unmarshal(m, b)
}
func (m *DeleteMarketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMarketsResponse.Marshal(b, m, deterministic)
}
func (m *DeleteMarketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMarketsResponse.Merge(m, src)
}
func (m *DeleteMarketsResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteMarketsResponse.Size(m)
}
func (m *DeleteMarketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMarketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMarketsResponse proto.InternalMessageInfo

func (m *DeleteMarketsResponse) GetMarketId() []string {
	if m != nil {
		return m.MarketId
	}
	return nil
}

type UserJoinMarketRequest struct {
	MarketId             []string `protobuf:"bytes,1,rep,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	UserId               []string `protobuf:"bytes,2,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserJoinMarketRequest) Reset()         { *m = UserJoinMarketRequest{} }
func (m *UserJoinMarketRequest) String() string { return proto.CompactTextString(m) }
func (*UserJoinMarketRequest) ProtoMessage()    {}
func (*UserJoinMarketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{9}
}

func (m *UserJoinMarketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserJoinMarketRequest.Unmarshal(m, b)
}
func (m *UserJoinMarketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserJoinMarketRequest.Marshal(b, m, deterministic)
}
func (m *UserJoinMarketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserJoinMarketRequest.Merge(m, src)
}
func (m *UserJoinMarketRequest) XXX_Size() int {
	return xxx_messageInfo_UserJoinMarketRequest.Size(m)
}
func (m *UserJoinMarketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserJoinMarketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserJoinMarketRequest proto.InternalMessageInfo

func (m *UserJoinMarketRequest) GetMarketId() []string {
	if m != nil {
		return m.MarketId
	}
	return nil
}

func (m *UserJoinMarketRequest) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

type UserJoinMarketResponse struct {
	MarketId             []string `protobuf:"bytes,1,rep,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	UserId               []string `protobuf:"bytes,2,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserJoinMarketResponse) Reset()         { *m = UserJoinMarketResponse{} }
func (m *UserJoinMarketResponse) String() string { return proto.CompactTextString(m) }
func (*UserJoinMarketResponse) ProtoMessage()    {}
func (*UserJoinMarketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{10}
}

func (m *UserJoinMarketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserJoinMarketResponse.Unmarshal(m, b)
}
func (m *UserJoinMarketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserJoinMarketResponse.Marshal(b, m, deterministic)
}
func (m *UserJoinMarketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserJoinMarketResponse.Merge(m, src)
}
func (m *UserJoinMarketResponse) XXX_Size() int {
	return xxx_messageInfo_UserJoinMarketResponse.Size(m)
}
func (m *UserJoinMarketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserJoinMarketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserJoinMarketResponse proto.InternalMessageInfo

func (m *UserJoinMarketResponse) GetMarketId() []string {
	if m != nil {
		return m.MarketId
	}
	return nil
}

func (m *UserJoinMarketResponse) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

type UserLeaveMarketRequest struct {
	MarketId             []string `protobuf:"bytes,1,rep,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	UserId               []string `protobuf:"bytes,2,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLeaveMarketRequest) Reset()         { *m = UserLeaveMarketRequest{} }
func (m *UserLeaveMarketRequest) String() string { return proto.CompactTextString(m) }
func (*UserLeaveMarketRequest) ProtoMessage()    {}
func (*UserLeaveMarketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{11}
}

func (m *UserLeaveMarketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLeaveMarketRequest.Unmarshal(m, b)
}
func (m *UserLeaveMarketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLeaveMarketRequest.Marshal(b, m, deterministic)
}
func (m *UserLeaveMarketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLeaveMarketRequest.Merge(m, src)
}
func (m *UserLeaveMarketRequest) XXX_Size() int {
	return xxx_messageInfo_UserLeaveMarketRequest.Size(m)
}
func (m *UserLeaveMarketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLeaveMarketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLeaveMarketRequest proto.InternalMessageInfo

func (m *UserLeaveMarketRequest) GetMarketId() []string {
	if m != nil {
		return m.MarketId
	}
	return nil
}

func (m *UserLeaveMarketRequest) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

type UserLeaveMarketResponse struct {
	MarketId             []string `protobuf:"bytes,1,rep,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	UserId               []string `protobuf:"bytes,2,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLeaveMarketResponse) Reset()         { *m = UserLeaveMarketResponse{} }
func (m *UserLeaveMarketResponse) String() string { return proto.CompactTextString(m) }
func (*UserLeaveMarketResponse) ProtoMessage()    {}
func (*UserLeaveMarketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{12}
}

func (m *UserLeaveMarketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLeaveMarketResponse.Unmarshal(m, b)
}
func (m *UserLeaveMarketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLeaveMarketResponse.Marshal(b, m, deterministic)
}
func (m *UserLeaveMarketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLeaveMarketResponse.Merge(m, src)
}
func (m *UserLeaveMarketResponse) XXX_Size() int {
	return xxx_messageInfo_UserLeaveMarketResponse.Size(m)
}
func (m *UserLeaveMarketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLeaveMarketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLeaveMarketResponse proto.InternalMessageInfo

func (m *UserLeaveMarketResponse) GetMarketId() []string {
	if m != nil {
		return m.MarketId
	}
	return nil
}

func (m *UserLeaveMarketResponse) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

type MarketUser struct {
	MarketId             *wrappers.StringValue `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	UserId               *wrappers.StringValue `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Owner                *wrappers.StringValue `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	CreateTime           *timestamp.Timestamp  `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MarketUser) Reset()         { *m = MarketUser{} }
func (m *MarketUser) String() string { return proto.CompactTextString(m) }
func (*MarketUser) ProtoMessage()    {}
func (*MarketUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{13}
}

func (m *MarketUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketUser.Unmarshal(m, b)
}
func (m *MarketUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketUser.Marshal(b, m, deterministic)
}
func (m *MarketUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketUser.Merge(m, src)
}
func (m *MarketUser) XXX_Size() int {
	return xxx_messageInfo_MarketUser.Size(m)
}
func (m *MarketUser) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketUser.DiscardUnknown(m)
}

var xxx_messageInfo_MarketUser proto.InternalMessageInfo

func (m *MarketUser) GetMarketId() *wrappers.StringValue {
	if m != nil {
		return m.MarketId
	}
	return nil
}

func (m *MarketUser) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *MarketUser) GetOwner() *wrappers.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *MarketUser) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type DescribeMarketUsersRequest struct {
	Limit                uint32                `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32                `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	SearchWord           *wrappers.StringValue `protobuf:"bytes,3,opt,name=search_word,json=searchWord,proto3" json:"search_word,omitempty"`
	SortKey              *wrappers.StringValue `protobuf:"bytes,4,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
	Reverse              *wrappers.BoolValue   `protobuf:"bytes,5,opt,name=reverse,proto3" json:"reverse,omitempty"`
	MarketId             []string              `protobuf:"bytes,11,rep,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	UserId               []string              `protobuf:"bytes,12,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Owner                []string              `protobuf:"bytes,13,rep,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DescribeMarketUsersRequest) Reset()         { *m = DescribeMarketUsersRequest{} }
func (m *DescribeMarketUsersRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeMarketUsersRequest) ProtoMessage()    {}
func (*DescribeMarketUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{14}
}

func (m *DescribeMarketUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeMarketUsersRequest.Unmarshal(m, b)
}
func (m *DescribeMarketUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeMarketUsersRequest.Marshal(b, m, deterministic)
}
func (m *DescribeMarketUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeMarketUsersRequest.Merge(m, src)
}
func (m *DescribeMarketUsersRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeMarketUsersRequest.Size(m)
}
func (m *DescribeMarketUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeMarketUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeMarketUsersRequest proto.InternalMessageInfo

func (m *DescribeMarketUsersRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeMarketUsersRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeMarketUsersRequest) GetSearchWord() *wrappers.StringValue {
	if m != nil {
		return m.SearchWord
	}
	return nil
}

func (m *DescribeMarketUsersRequest) GetSortKey() *wrappers.StringValue {
	if m != nil {
		return m.SortKey
	}
	return nil
}

func (m *DescribeMarketUsersRequest) GetReverse() *wrappers.BoolValue {
	if m != nil {
		return m.Reverse
	}
	return nil
}

func (m *DescribeMarketUsersRequest) GetMarketId() []string {
	if m != nil {
		return m.MarketId
	}
	return nil
}

func (m *DescribeMarketUsersRequest) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *DescribeMarketUsersRequest) GetOwner() []string {
	if m != nil {
		return m.Owner
	}
	return nil
}

type DescribeMarketUsersResponse struct {
	TotalCount           uint32        `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	MarketUserSet        []*MarketUser `protobuf:"bytes,2,rep,name=market_user_set,json=marketUserSet,proto3" json:"market_user_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DescribeMarketUsersResponse) Reset()         { *m = DescribeMarketUsersResponse{} }
func (m *DescribeMarketUsersResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeMarketUsersResponse) ProtoMessage()    {}
func (*DescribeMarketUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{15}
}

func (m *DescribeMarketUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeMarketUsersResponse.Unmarshal(m, b)
}
func (m *DescribeMarketUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeMarketUsersResponse.Marshal(b, m, deterministic)
}
func (m *DescribeMarketUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeMarketUsersResponse.Merge(m, src)
}
func (m *DescribeMarketUsersResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeMarketUsersResponse.Size(m)
}
func (m *DescribeMarketUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeMarketUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeMarketUsersResponse proto.InternalMessageInfo

func (m *DescribeMarketUsersResponse) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *DescribeMarketUsersResponse) GetMarketUserSet() []*MarketUser {
	if m != nil {
		return m.MarketUserSet
	}
	return nil
}

func init() {
	proto.RegisterType((*Market)(nil), "openpitrix.Market")
	proto.RegisterType((*CreateMarketRequest)(nil), "openpitrix.CreateMarketRequest")
	proto.RegisterType((*CreateMarketResponse)(nil), "openpitrix.CreateMarketResponse")
	proto.RegisterType((*DescribeMarketsRequest)(nil), "openpitrix.DescribeMarketsRequest")
	proto.RegisterType((*DescribeMarketsResponse)(nil), "openpitrix.DescribeMarketsResponse")
	proto.RegisterType((*ModifyMarketRequest)(nil), "openpitrix.ModifyMarketRequest")
	proto.RegisterType((*ModifyMarketResponse)(nil), "openpitrix.ModifyMarketResponse")
	proto.RegisterType((*DeleteMarketsRequest)(nil), "openpitrix.DeleteMarketsRequest")
	proto.RegisterType((*DeleteMarketsResponse)(nil), "openpitrix.DeleteMarketsResponse")
	proto.RegisterType((*UserJoinMarketRequest)(nil), "openpitrix.UserJoinMarketRequest")
	proto.RegisterType((*UserJoinMarketResponse)(nil), "openpitrix.UserJoinMarketResponse")
	proto.RegisterType((*UserLeaveMarketRequest)(nil), "openpitrix.UserLeaveMarketRequest")
	proto.RegisterType((*UserLeaveMarketResponse)(nil), "openpitrix.UserLeaveMarketResponse")
	proto.RegisterType((*MarketUser)(nil), "openpitrix.MarketUser")
	proto.RegisterType((*DescribeMarketUsersRequest)(nil), "openpitrix.DescribeMarketUsersRequest")
	proto.RegisterType((*DescribeMarketUsersResponse)(nil), "openpitrix.DescribeMarketUsersResponse")
}

func init() { proto.RegisterFile("market.proto", fileDescriptor_3f90997f23a2c3f8) }

var fileDescriptor_3f90997f23a2c3f8 = []byte{
	// 1047 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xd6, 0xae, 0x93, 0x38, 0x7d, 0x9d, 0x8d, 0xd3, 0x49, 0xe2, 0x58, 0x9b, 0x28, 0x31, 0x8b,
	0x04, 0xa1, 0xa2, 0x76, 0xeb, 0x06, 0x55, 0x7c, 0x55, 0x72, 0xdb, 0x4b, 0x81, 0x80, 0x70, 0xf8,
	0x90, 0xb8, 0x58, 0x6b, 0x7b, 0xec, 0x2e, 0xb5, 0x77, 0x96, 0x99, 0x71, 0x4c, 0x84, 0x04, 0x12,
	0x37, 0x2e, 0x08, 0x99, 0x1f, 0xc0, 0xbf, 0xe0, 0x17, 0xc0, 0x2f, 0xe0, 0xc0, 0x85, 0x23, 0x77,
	0xae, 0x1c, 0xd1, 0x7c, 0xd8, 0x99, 0xdd, 0x75, 0x9c, 0x4d, 0xc3, 0x01, 0x71, 0x4a, 0x3c, 0xef,
	0xf3, 0xbe, 0xf3, 0xcc, 0xf3, 0x7e, 0x2d, 0xac, 0x0d, 0x7d, 0xfa, 0x0c, 0xf3, 0x6a, 0x44, 0x09,
	0x27, 0x08, 0x48, 0x84, 0xc3, 0x28, 0xe0, 0x34, 0xf8, 0xd2, 0xdd, 0xef, 0x13, 0xd2, 0x1f, 0xe0,
	0x9a, 0xb4, 0xb4, 0x47, 0xbd, 0xda, 0x98, 0xfa, 0x51, 0x84, 0x29, 0x53, 0x58, 0xf7, 0x20, 0x69,
	0xe7, 0xc1, 0x10, 0x33, 0xee, 0x0f, 0x23, 0x0d, 0xd8, 0xd3, 0x00, 0x3f, 0x0a, 0x6a, 0x7e, 0x18,
	0x12, 0xee, 0xf3, 0x80, 0x84, 0x53, 0xf7, 0x57, 0xe5, 0x9f, 0xce, 0xed, 0x3e, 0x0e, 0x6f, 0xb3,
	0xb1, 0xdf, 0xef, 0x63, 0x5a, 0x23, 0x91, 0x44, 0xa4, 0xd1, 0xde, 0xef, 0x39, 0x58, 0x39, 0x96,
	0x4c, 0xd1, 0xeb, 0x70, 0x43, 0x71, 0x6e, 0x05, 0xdd, 0xb2, 0x55, 0xb1, 0x0e, 0x0b, 0xf5, 0xbd,
	0xaa, 0xba, 0xaa, 0x3a, 0xe5, 0x52, 0x3d, 0xe1, 0x34, 0x08, 0xfb, 0x9f, 0xf8, 0x83, 0x11, 0x6e,
	0xae, 0x2a, 0xf8, 0x93, 0x2e, 0xba, 0x03, 0x4b, 0xa1, 0x3f, 0xc4, 0x65, 0x3b, 0x83, 0x97, 0x44,
	0xa2, 0xb7, 0x00, 0x4e, 0x03, 0x16, 0xb4, 0x83, 0x41, 0xc0, 0xcf, 0xca, 0xb9, 0x0c, 0x7e, 0x06,
	0x1e, 0x1d, 0xc1, 0x0a, 0xe3, 0x3e, 0x1f, 0xb1, 0xf2, 0x52, 0x06, 0x4f, 0x8d, 0x45, 0x75, 0x58,
	0x26, 0xe3, 0x10, 0xd3, 0xf2, 0x72, 0x06, 0x27, 0x05, 0x45, 0x0f, 0xa0, 0xd0, 0xc5, 0xac, 0x43,
	0x03, 0xa9, 0x60, 0x79, 0x25, 0x83, 0xa7, 0xe9, 0x80, 0xde, 0x84, 0x42, 0x87, 0x62, 0x9f, 0xe3,
	0x96, 0xc8, 0x62, 0x39, 0x2f, 0xfd, 0xdd, 0x94, 0xff, 0x47, 0xd3, 0x14, 0x37, 0x41, 0xc1, 0xc5,
	0x81, 0x70, 0x56, 0xd4, 0x95, 0xf3, 0xea, 0xe5, 0xce, 0x0a, 0x2e, 0x0e, 0xbc, 0x5f, 0x2d, 0xd8,
	0x7c, 0x24, 0x63, 0xa9, 0xfc, 0x36, 0xf1, 0x17, 0x23, 0xcc, 0xf8, 0x2c, 0x57, 0xd6, 0x73, 0xe6,
	0xca, 0xbe, 0x62, 0xae, 0x12, 0x0a, 0xe6, 0xae, 0xa8, 0xa0, 0xf7, 0x21, 0x6c, 0xc5, 0x9f, 0xc1,
	0x22, 0x12, 0x32, 0x7c, 0x8d, 0x72, 0xf5, 0xfe, 0xb6, 0xa1, 0xf4, 0x58, 0x5e, 0xd1, 0xd6, 0x51,
	0xd9, 0x54, 0x9d, 0xb7, 0xa1, 0xc0, 0xb0, 0x4f, 0x3b, 0x4f, 0x5b, 0x63, 0x42, 0xb3, 0xc5, 0x05,
	0xe5, 0xf0, 0x29, 0xa1, 0x5d, 0xb4, 0x05, 0xcb, 0x83, 0x60, 0x18, 0x70, 0xa9, 0x92, 0xd3, 0x54,
	0x3f, 0x50, 0x09, 0x56, 0x48, 0xaf, 0xc7, 0x30, 0x97, 0xaf, 0x77, 0x9a, 0xfa, 0x17, 0xba, 0x0f,
	0xab, 0x8c, 0x50, 0xde, 0x7a, 0x86, 0xcf, 0x32, 0x15, 0x72, 0x5e, 0xa0, 0xdf, 0xc5, 0xa2, 0xfe,
	0xf3, 0x14, 0x9f, 0x62, 0xca, 0xb0, 0xae, 0xe5, 0x74, 0x51, 0x3c, 0x24, 0x64, 0xa0, 0xbd, 0x34,
	0x14, 0xed, 0x9a, 0x8a, 0x15, 0x2a, 0xb9, 0xc3, 0x1b, 0x46, 0x0b, 0xef, 0xc7, 0x92, 0xbc, 0x26,
	0xad, 0x66, 0x1a, 0x4b, 0xb3, 0x96, 0x73, 0xa4, 0x6d, 0xda, 0x54, 0x5b, 0xd3, 0xa6, 0x5a, 0x97,
	0xc7, 0xba, 0x6d, 0x76, 0x20, 0x3f, 0x62, 0x98, 0x8a, 0x8b, 0x8a, 0x0a, 0x2e, 0x7e, 0x3e, 0xe9,
	0x7a, 0x43, 0xd8, 0x49, 0x29, 0xaf, 0x13, 0x7a, 0x00, 0x05, 0x4e, 0xb8, 0x3f, 0x68, 0x75, 0xc8,
	0x28, 0xe4, 0x52, 0x7a, 0xa7, 0x09, 0xf2, 0xe8, 0x91, 0x38, 0x41, 0x77, 0x01, 0x34, 0x7f, 0x21,
	0xa5, 0x5d, 0xc9, 0x1d, 0x16, 0xea, 0xa8, 0x7a, 0x3e, 0x59, 0xab, 0xba, 0x42, 0xf4, 0x2b, 0x4f,
	0x30, 0xf7, 0x7e, 0xb6, 0x61, 0xf3, 0x98, 0x74, 0x83, 0xde, 0x59, 0xbc, 0x09, 0xfe, 0xf7, 0xb3,
	0x2e, 0xd1, 0x75, 0xcb, 0xcf, 0xd1, 0x75, 0x71, 0xdd, 0xae, 0xdf, 0x75, 0xf7, 0x60, 0xeb, 0x31,
	0x1e, 0x60, 0x9e, 0x6c, 0xb9, 0xdd, 0x78, 0xc8, 0x58, 0x59, 0x7a, 0x47, 0xb0, 0x9d, 0x70, 0xd2,
	0x44, 0x16, 0x7a, 0x1d, 0xc3, 0xf6, 0xc7, 0x0c, 0xd3, 0x77, 0x48, 0x10, 0xc6, 0xf3, 0xbe, 0xc8,
	0xcb, 0x2c, 0x5a, 0x3b, 0x56, 0xb4, 0xef, 0x43, 0x29, 0x19, 0x2e, 0x03, 0x8b, 0x4b, 0xe3, 0xbd,
	0x87, 0xfd, 0x53, 0xfc, 0x6f, 0xf0, 0xfb, 0x00, 0x76, 0x52, 0xf1, 0xae, 0x45, 0xf0, 0x2f, 0x0b,
	0x40, 0x05, 0x12, 0x71, 0xaf, 0xd3, 0x2d, 0xaf, 0x99, 0x57, 0x64, 0x28, 0x5f, 0x45, 0xe0, 0x7c,
	0x55, 0xe7, 0xb2, 0xaf, 0xea, 0xc4, 0xaa, 0x5d, 0xba, 0xca, 0xaa, 0xf5, 0x7e, 0xb1, 0xc1, 0x8d,
	0x0f, 0x26, 0xf1, 0xf2, 0x59, 0x8d, 0xce, 0xe6, 0xba, 0x35, 0x7f, 0xae, 0xdb, 0xb1, 0xb9, 0x9e,
	0x58, 0x22, 0xb9, 0x2b, 0x2e, 0x91, 0xff, 0xd2, 0x5a, 0x30, 0x4a, 0x64, 0xcd, 0x2c, 0x91, 0xf3,
	0xb9, 0xef, 0x18, 0x73, 0xdf, 0xfb, 0x1a, 0x76, 0xe7, 0xaa, 0x98, 0x75, 0xc4, 0x3f, 0x80, 0xa2,
	0xe6, 0x22, 0x6f, 0x3d, 0x9f, 0xf3, 0xa5, 0xf4, 0x9c, 0x17, 0xa1, 0x9b, 0xce, 0x70, 0xf6, 0xff,
	0x09, 0xe6, 0xf5, 0x3f, 0xf2, 0xe0, 0x28, 0xeb, 0xb1, 0x1f, 0xfa, 0x7d, 0x4c, 0xd1, 0x57, 0xb0,
	0x66, 0x7e, 0x3e, 0xa0, 0x03, 0x33, 0xd0, 0x9c, 0xef, 0x23, 0xb7, 0x72, 0x31, 0x40, 0xbd, 0xc2,
	0x3b, 0x9c, 0x34, 0x8a, 0xc8, 0x51, 0xc5, 0x53, 0x51, 0xf7, 0x7f, 0xfb, 0xdb, 0x9f, 0x3f, 0xda,
	0x1b, 0x5e, 0xa1, 0x76, 0x7a, 0xb7, 0xa6, 0x4e, 0xd8, 0x1b, 0xd6, 0x2d, 0xf4, 0x83, 0x05, 0xc5,
	0xc4, 0xba, 0x43, 0x9e, 0x19, 0x7f, 0xfe, 0x57, 0x88, 0xfb, 0xe2, 0x42, 0x8c, 0xa6, 0x71, 0x34,
	0x69, 0xec, 0xa3, 0xbd, 0xae, 0xb6, 0x6a, 0x22, 0xac, 0x32, 0x0e, 0xf8, 0xd3, 0x4a, 0x2f, 0x18,
	0x70, 0x4c, 0x25, 0x2b, 0x07, 0x99, 0xac, 0x84, 0x1e, 0xe6, 0x60, 0x8f, 0xeb, 0x31, 0x67, 0x55,
	0xc6, 0xf5, 0x98, 0xb7, 0x13, 0xb4, 0x1e, 0x43, 0x69, 0x8a, 0xe9, 0x51, 0x4f, 0xea, 0xf1, 0x0d,
	0x38, 0xb1, 0x69, 0x8e, 0x2a, 0xf1, 0x87, 0xa6, 0xb7, 0x83, 0xfb, 0xc2, 0x02, 0x84, 0xbe, 0xff,
	0x95, 0x49, 0x63, 0x03, 0xad, 0x77, 0xa5, 0x6d, 0x2a, 0x83, 0x22, 0x70, 0x2b, 0x49, 0xe0, 0x3b,
	0x0b, 0xd6, 0xe3, 0xa3, 0x1c, 0xc5, 0x2e, 0x98, 0xbb, 0x35, 0x5c, 0x6f, 0x11, 0x44, 0x93, 0xb8,
	0x33, 0x69, 0x20, 0xb4, 0x21, 0xaa, 0xb6, 0xf2, 0x39, 0x09, 0x42, 0x53, 0x87, 0x6d, 0x6f, 0xc3,
	0xa4, 0x21, 0xcc, 0x82, 0xcb, 0xf7, 0x16, 0x14, 0x13, 0x63, 0x1b, 0xa5, 0x6e, 0x4a, 0xef, 0x88,
	0x78, 0x71, 0x5c, 0x30, 0xf7, 0xbd, 0xfa, 0xa4, 0xb1, 0x89, 0x6e, 0x4a, 0x3a, 0x03, 0x61, 0x36,
	0xf9, 0x94, 0xbc, 0x9b, 0x26, 0x1f, 0x69, 0x17, 0x84, 0x7e, 0xb2, 0x60, 0x73, 0x4e, 0xf7, 0xa2,
	0x97, 0x2e, 0xae, 0x46, 0x73, 0x48, 0xba, 0x2f, 0x5f, 0x8a, 0xd3, 0xe4, 0xee, 0x4f, 0x1a, 0x7b,
	0xc8, 0x9d, 0x55, 0xae, 0x60, 0x99, 0xae, 0x5b, 0x84, 0x0c, 0xd5, 0xe4, 0x38, 0x60, 0x0f, 0x97,
	0x3e, 0xb3, 0xa3, 0x76, 0x7b, 0x45, 0x4e, 0xb3, 0x7b, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7b,
	0x6e, 0xe2, 0x1f, 0x63, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MarketManagerClient is the client API for MarketManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketManagerClient interface {
	CreateMarket(ctx context.Context, in *CreateMarketRequest, opts ...grpc.CallOption) (*CreateMarketResponse, error)
	DescribeMarkets(ctx context.Context, in *DescribeMarketsRequest, opts ...grpc.CallOption) (*DescribeMarketsResponse, error)
	ModifyMarket(ctx context.Context, in *ModifyMarketRequest, opts ...grpc.CallOption) (*ModifyMarketResponse, error)
	DeleteMarkets(ctx context.Context, in *DeleteMarketsRequest, opts ...grpc.CallOption) (*DeleteMarketsResponse, error)
	UserJoinMarket(ctx context.Context, in *UserJoinMarketRequest, opts ...grpc.CallOption) (*UserJoinMarketResponse, error)
	UserLeaveMarket(ctx context.Context, in *UserLeaveMarketRequest, opts ...grpc.CallOption) (*UserLeaveMarketResponse, error)
	DescribeMarketUsers(ctx context.Context, in *DescribeMarketUsersRequest, opts ...grpc.CallOption) (*DescribeMarketUsersResponse, error)
}

type marketManagerClient struct {
	cc *grpc.ClientConn
}

func NewMarketManagerClient(cc *grpc.ClientConn) MarketManagerClient {
	return &marketManagerClient{cc}
}

func (c *marketManagerClient) CreateMarket(ctx context.Context, in *CreateMarketRequest, opts ...grpc.CallOption) (*CreateMarketResponse, error) {
	out := new(CreateMarketResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.MarketManager/CreateMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketManagerClient) DescribeMarkets(ctx context.Context, in *DescribeMarketsRequest, opts ...grpc.CallOption) (*DescribeMarketsResponse, error) {
	out := new(DescribeMarketsResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.MarketManager/DescribeMarkets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketManagerClient) ModifyMarket(ctx context.Context, in *ModifyMarketRequest, opts ...grpc.CallOption) (*ModifyMarketResponse, error) {
	out := new(ModifyMarketResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.MarketManager/ModifyMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketManagerClient) DeleteMarkets(ctx context.Context, in *DeleteMarketsRequest, opts ...grpc.CallOption) (*DeleteMarketsResponse, error) {
	out := new(DeleteMarketsResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.MarketManager/DeleteMarkets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketManagerClient) UserJoinMarket(ctx context.Context, in *UserJoinMarketRequest, opts ...grpc.CallOption) (*UserJoinMarketResponse, error) {
	out := new(UserJoinMarketResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.MarketManager/UserJoinMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketManagerClient) UserLeaveMarket(ctx context.Context, in *UserLeaveMarketRequest, opts ...grpc.CallOption) (*UserLeaveMarketResponse, error) {
	out := new(UserLeaveMarketResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.MarketManager/UserLeaveMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketManagerClient) DescribeMarketUsers(ctx context.Context, in *DescribeMarketUsersRequest, opts ...grpc.CallOption) (*DescribeMarketUsersResponse, error) {
	out := new(DescribeMarketUsersResponse)
	err := c.cc.Invoke(ctx, "/openpitrix.MarketManager/DescribeMarketUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketManagerServer is the server API for MarketManager service.
type MarketManagerServer interface {
	CreateMarket(context.Context, *CreateMarketRequest) (*CreateMarketResponse, error)
	DescribeMarkets(context.Context, *DescribeMarketsRequest) (*DescribeMarketsResponse, error)
	ModifyMarket(context.Context, *ModifyMarketRequest) (*ModifyMarketResponse, error)
	DeleteMarkets(context.Context, *DeleteMarketsRequest) (*DeleteMarketsResponse, error)
	UserJoinMarket(context.Context, *UserJoinMarketRequest) (*UserJoinMarketResponse, error)
	UserLeaveMarket(context.Context, *UserLeaveMarketRequest) (*UserLeaveMarketResponse, error)
	DescribeMarketUsers(context.Context, *DescribeMarketUsersRequest) (*DescribeMarketUsersResponse, error)
}

func RegisterMarketManagerServer(s *grpc.Server, srv MarketManagerServer) {
	s.RegisterService(&_MarketManager_serviceDesc, srv)
}

func _MarketManager_CreateMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketManagerServer).CreateMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.MarketManager/CreateMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketManagerServer).CreateMarket(ctx, req.(*CreateMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketManager_DescribeMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketManagerServer).DescribeMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.MarketManager/DescribeMarkets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketManagerServer).DescribeMarkets(ctx, req.(*DescribeMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketManager_ModifyMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketManagerServer).ModifyMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.MarketManager/ModifyMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketManagerServer).ModifyMarket(ctx, req.(*ModifyMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketManager_DeleteMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketManagerServer).DeleteMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.MarketManager/DeleteMarkets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketManagerServer).DeleteMarkets(ctx, req.(*DeleteMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketManager_UserJoinMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserJoinMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketManagerServer).UserJoinMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.MarketManager/UserJoinMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketManagerServer).UserJoinMarket(ctx, req.(*UserJoinMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketManager_UserLeaveMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLeaveMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketManagerServer).UserLeaveMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.MarketManager/UserLeaveMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketManagerServer).UserLeaveMarket(ctx, req.(*UserLeaveMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketManager_DescribeMarketUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeMarketUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketManagerServer).DescribeMarketUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.MarketManager/DescribeMarketUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketManagerServer).DescribeMarketUsers(ctx, req.(*DescribeMarketUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openpitrix.MarketManager",
	HandlerType: (*MarketManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMarket",
			Handler:    _MarketManager_CreateMarket_Handler,
		},
		{
			MethodName: "DescribeMarkets",
			Handler:    _MarketManager_DescribeMarkets_Handler,
		},
		{
			MethodName: "ModifyMarket",
			Handler:    _MarketManager_ModifyMarket_Handler,
		},
		{
			MethodName: "DeleteMarkets",
			Handler:    _MarketManager_DeleteMarkets_Handler,
		},
		{
			MethodName: "UserJoinMarket",
			Handler:    _MarketManager_UserJoinMarket_Handler,
		},
		{
			MethodName: "UserLeaveMarket",
			Handler:    _MarketManager_UserLeaveMarket_Handler,
		},
		{
			MethodName: "DescribeMarketUsers",
			Handler:    _MarketManager_DescribeMarketUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market.proto",
}
