// Code generated by protoc-gen-go. DO NOT EDIT.
// source: runtime_env.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/wrappers"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RuntimeEnv struct {
	RuntimeEnvId           *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=runtime_env_id,json=runtimeEnvId" json:"runtime_env_id,omitempty"`
	Name                   *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description            *google_protobuf.StringValue `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	RuntimeEnvUrl          *google_protobuf.StringValue `protobuf:"bytes,4,opt,name=runtime_env_url,json=runtimeEnvUrl" json:"runtime_env_url,omitempty"`
	RuntimeEnvCredentialId *google_protobuf.StringValue `protobuf:"bytes,5,opt,name=runtime_env_credential_id,json=runtimeEnvCredentialId" json:"runtime_env_credential_id,omitempty"`
	Labels                 *google_protobuf.StringValue `protobuf:"bytes,6,opt,name=labels" json:"labels,omitempty"`
	Owner                  *google_protobuf.StringValue `protobuf:"bytes,7,opt,name=owner" json:"owner,omitempty"`
	Status                 *google_protobuf.StringValue `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	CreateTime             *google_protobuf1.Timestamp  `protobuf:"bytes,9,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	StatusTime             *google_protobuf1.Timestamp  `protobuf:"bytes,10,opt,name=status_time,json=statusTime" json:"status_time,omitempty"`
}

func (m *RuntimeEnv) Reset()                    { *m = RuntimeEnv{} }
func (m *RuntimeEnv) String() string            { return proto.CompactTextString(m) }
func (*RuntimeEnv) ProtoMessage()               {}
func (*RuntimeEnv) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *RuntimeEnv) GetRuntimeEnvId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvId
	}
	return nil
}

func (m *RuntimeEnv) GetName() *google_protobuf.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RuntimeEnv) GetDescription() *google_protobuf.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *RuntimeEnv) GetRuntimeEnvUrl() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvUrl
	}
	return nil
}

func (m *RuntimeEnv) GetRuntimeEnvCredentialId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvCredentialId
	}
	return nil
}

func (m *RuntimeEnv) GetLabels() *google_protobuf.StringValue {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *RuntimeEnv) GetOwner() *google_protobuf.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *RuntimeEnv) GetStatus() *google_protobuf.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RuntimeEnv) GetCreateTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *RuntimeEnv) GetStatusTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type CreateRuntimeEnvRequest struct {
	Name          *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description   *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Labels        *google_protobuf.StringValue `protobuf:"bytes,3,opt,name=labels" json:"labels,omitempty"`
	RuntimeEnvUrl *google_protobuf.StringValue `protobuf:"bytes,4,opt,name=runtime_env_url,json=runtimeEnvUrl" json:"runtime_env_url,omitempty"`
}

func (m *CreateRuntimeEnvRequest) Reset()                    { *m = CreateRuntimeEnvRequest{} }
func (m *CreateRuntimeEnvRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRuntimeEnvRequest) ProtoMessage()               {}
func (*CreateRuntimeEnvRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *CreateRuntimeEnvRequest) GetName() *google_protobuf.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *CreateRuntimeEnvRequest) GetDescription() *google_protobuf.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *CreateRuntimeEnvRequest) GetLabels() *google_protobuf.StringValue {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CreateRuntimeEnvRequest) GetRuntimeEnvUrl() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvUrl
	}
	return nil
}

type CreateRuntimeEnvResponse struct {
	RuntimeEnv *RuntimeEnv `protobuf:"bytes,1,opt,name=runtime_env,json=runtimeEnv" json:"runtime_env,omitempty"`
}

func (m *CreateRuntimeEnvResponse) Reset()                    { *m = CreateRuntimeEnvResponse{} }
func (m *CreateRuntimeEnvResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateRuntimeEnvResponse) ProtoMessage()               {}
func (*CreateRuntimeEnvResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *CreateRuntimeEnvResponse) GetRuntimeEnv() *RuntimeEnv {
	if m != nil {
		return m.RuntimeEnv
	}
	return nil
}

type DescribeRuntimeEnvsRequest struct {
	RuntimeEnvId []*google_protobuf.StringValue `protobuf:"bytes,1,rep,name=runtime_env_id,json=runtimeEnvId" json:"runtime_env_id,omitempty"`
	Status       []*google_protobuf.StringValue `protobuf:"bytes,2,rep,name=status" json:"status,omitempty"`
	SearchWord   *google_protobuf.StringValue   `protobuf:"bytes,3,opt,name=search_word,json=searchWord" json:"search_word,omitempty"`
	Selector     *google_protobuf.StringValue   `protobuf:"bytes,4,opt,name=selector" json:"selector,omitempty"`
	Owner        []*google_protobuf.StringValue `protobuf:"bytes,5,rep,name=owner" json:"owner,omitempty"`
	Limit        *google_protobuf.UInt32Value   `protobuf:"bytes,6,opt,name=limit" json:"limit,omitempty"`
	Offset       *google_protobuf.UInt32Value   `protobuf:"bytes,7,opt,name=offset" json:"offset,omitempty"`
	Verbose      *google_protobuf.UInt32Value   `protobuf:"bytes,8,opt,name=verbose" json:"verbose,omitempty"`
}

func (m *DescribeRuntimeEnvsRequest) Reset()                    { *m = DescribeRuntimeEnvsRequest{} }
func (m *DescribeRuntimeEnvsRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeRuntimeEnvsRequest) ProtoMessage()               {}
func (*DescribeRuntimeEnvsRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *DescribeRuntimeEnvsRequest) GetRuntimeEnvId() []*google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvId
	}
	return nil
}

func (m *DescribeRuntimeEnvsRequest) GetStatus() []*google_protobuf.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeRuntimeEnvsRequest) GetSearchWord() *google_protobuf.StringValue {
	if m != nil {
		return m.SearchWord
	}
	return nil
}

func (m *DescribeRuntimeEnvsRequest) GetSelector() *google_protobuf.StringValue {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *DescribeRuntimeEnvsRequest) GetOwner() []*google_protobuf.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *DescribeRuntimeEnvsRequest) GetLimit() *google_protobuf.UInt32Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *DescribeRuntimeEnvsRequest) GetOffset() *google_protobuf.UInt32Value {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *DescribeRuntimeEnvsRequest) GetVerbose() *google_protobuf.UInt32Value {
	if m != nil {
		return m.Verbose
	}
	return nil
}

type DescribeRuntimeEnvsResponse struct {
	TotalCount    *google_protobuf.UInt32Value `protobuf:"bytes,1,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	RuntimeEnvSet []*RuntimeEnv                `protobuf:"bytes,2,rep,name=runtime_env_set,json=runtimeEnvSet" json:"runtime_env_set,omitempty"`
}

func (m *DescribeRuntimeEnvsResponse) Reset()                    { *m = DescribeRuntimeEnvsResponse{} }
func (m *DescribeRuntimeEnvsResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeRuntimeEnvsResponse) ProtoMessage()               {}
func (*DescribeRuntimeEnvsResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *DescribeRuntimeEnvsResponse) GetTotalCount() *google_protobuf.UInt32Value {
	if m != nil {
		return m.TotalCount
	}
	return nil
}

func (m *DescribeRuntimeEnvsResponse) GetRuntimeEnvSet() []*RuntimeEnv {
	if m != nil {
		return m.RuntimeEnvSet
	}
	return nil
}

type ModifyRuntimeEnvRequest struct {
	RuntimeEnvId *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=runtime_env_id,json=runtimeEnvId" json:"runtime_env_id,omitempty"`
	Name         *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description  *google_protobuf.StringValue `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Labels       *google_protobuf.StringValue `protobuf:"bytes,4,opt,name=labels" json:"labels,omitempty"`
}

func (m *ModifyRuntimeEnvRequest) Reset()                    { *m = ModifyRuntimeEnvRequest{} }
func (m *ModifyRuntimeEnvRequest) String() string            { return proto.CompactTextString(m) }
func (*ModifyRuntimeEnvRequest) ProtoMessage()               {}
func (*ModifyRuntimeEnvRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *ModifyRuntimeEnvRequest) GetRuntimeEnvId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvId
	}
	return nil
}

func (m *ModifyRuntimeEnvRequest) GetName() *google_protobuf.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ModifyRuntimeEnvRequest) GetDescription() *google_protobuf.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ModifyRuntimeEnvRequest) GetLabels() *google_protobuf.StringValue {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ModifyRuntimeEnvResponse struct {
	RuntimeEnv *RuntimeEnv `protobuf:"bytes,1,opt,name=runtime_env,json=runtimeEnv" json:"runtime_env,omitempty"`
}

func (m *ModifyRuntimeEnvResponse) Reset()                    { *m = ModifyRuntimeEnvResponse{} }
func (m *ModifyRuntimeEnvResponse) String() string            { return proto.CompactTextString(m) }
func (*ModifyRuntimeEnvResponse) ProtoMessage()               {}
func (*ModifyRuntimeEnvResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *ModifyRuntimeEnvResponse) GetRuntimeEnv() *RuntimeEnv {
	if m != nil {
		return m.RuntimeEnv
	}
	return nil
}

type DeleteRuntimeEnvRequest struct {
	RuntimeEnvId *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=runtime_env_id,json=runtimeEnvId" json:"runtime_env_id,omitempty"`
}

func (m *DeleteRuntimeEnvRequest) Reset()                    { *m = DeleteRuntimeEnvRequest{} }
func (m *DeleteRuntimeEnvRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRuntimeEnvRequest) ProtoMessage()               {}
func (*DeleteRuntimeEnvRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *DeleteRuntimeEnvRequest) GetRuntimeEnvId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvId
	}
	return nil
}

type DeleteRuntimeEnvResponse struct {
	RuntimeEnv *RuntimeEnv `protobuf:"bytes,1,opt,name=runtime_env,json=runtimeEnv" json:"runtime_env,omitempty"`
}

func (m *DeleteRuntimeEnvResponse) Reset()                    { *m = DeleteRuntimeEnvResponse{} }
func (m *DeleteRuntimeEnvResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteRuntimeEnvResponse) ProtoMessage()               {}
func (*DeleteRuntimeEnvResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *DeleteRuntimeEnvResponse) GetRuntimeEnv() *RuntimeEnv {
	if m != nil {
		return m.RuntimeEnv
	}
	return nil
}

type RuntimeEnvCredential struct {
	RuntimeEnvCredentialId *google_protobuf.StringValue   `protobuf:"bytes,1,opt,name=runtime_env_credential_id,json=runtimeEnvCredentialId" json:"runtime_env_credential_id,omitempty"`
	Name                   *google_protobuf.StringValue   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description            *google_protobuf.StringValue   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Content                map[string]string              `protobuf:"bytes,4,rep,name=content" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Owner                  *google_protobuf.StringValue   `protobuf:"bytes,5,opt,name=owner" json:"owner,omitempty"`
	RuntimeEnvIds          []*google_protobuf.StringValue `protobuf:"bytes,6,rep,name=runtime_env_ids,json=runtimeEnvIds" json:"runtime_env_ids,omitempty"`
	Status                 *google_protobuf.StringValue   `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
	CreateTime             *google_protobuf1.Timestamp    `protobuf:"bytes,9,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	StatusTime             *google_protobuf1.Timestamp    `protobuf:"bytes,10,opt,name=status_time,json=statusTime" json:"status_time,omitempty"`
}

func (m *RuntimeEnvCredential) Reset()                    { *m = RuntimeEnvCredential{} }
func (m *RuntimeEnvCredential) String() string            { return proto.CompactTextString(m) }
func (*RuntimeEnvCredential) ProtoMessage()               {}
func (*RuntimeEnvCredential) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *RuntimeEnvCredential) GetRuntimeEnvCredentialId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvCredentialId
	}
	return nil
}

func (m *RuntimeEnvCredential) GetName() *google_protobuf.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RuntimeEnvCredential) GetDescription() *google_protobuf.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *RuntimeEnvCredential) GetContent() map[string]string {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *RuntimeEnvCredential) GetOwner() *google_protobuf.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *RuntimeEnvCredential) GetRuntimeEnvIds() []*google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvIds
	}
	return nil
}

func (m *RuntimeEnvCredential) GetStatus() *google_protobuf.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RuntimeEnvCredential) GetCreateTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *RuntimeEnvCredential) GetStatusTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type CreateRuntimeEnvCredentialRequset struct {
	Name        *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Content     map[string]string            `protobuf:"bytes,3,rep,name=content" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CreateRuntimeEnvCredentialRequset) Reset()         { *m = CreateRuntimeEnvCredentialRequset{} }
func (m *CreateRuntimeEnvCredentialRequset) String() string { return proto.CompactTextString(m) }
func (*CreateRuntimeEnvCredentialRequset) ProtoMessage()    {}
func (*CreateRuntimeEnvCredentialRequset) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{10}
}

func (m *CreateRuntimeEnvCredentialRequset) GetName() *google_protobuf.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *CreateRuntimeEnvCredentialRequset) GetDescription() *google_protobuf.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *CreateRuntimeEnvCredentialRequset) GetContent() map[string]string {
	if m != nil {
		return m.Content
	}
	return nil
}

type CreateRuntimeEnvCredentialResponse struct {
	RuntimeEnvCredential *RuntimeEnvCredential `protobuf:"bytes,1,opt,name=runtime_env_credential,json=runtimeEnvCredential" json:"runtime_env_credential,omitempty"`
}

func (m *CreateRuntimeEnvCredentialResponse) Reset()         { *m = CreateRuntimeEnvCredentialResponse{} }
func (m *CreateRuntimeEnvCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRuntimeEnvCredentialResponse) ProtoMessage()    {}
func (*CreateRuntimeEnvCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{11}
}

func (m *CreateRuntimeEnvCredentialResponse) GetRuntimeEnvCredential() *RuntimeEnvCredential {
	if m != nil {
		return m.RuntimeEnvCredential
	}
	return nil
}

type DescribeRuntimeEnvCredentialsRequset struct {
	RuntimeEnvCredentialId []*google_protobuf.StringValue `protobuf:"bytes,1,rep,name=runtime_env_credential_id,json=runtimeEnvCredentialId" json:"runtime_env_credential_id,omitempty"`
	Status                 []*google_protobuf.StringValue `protobuf:"bytes,2,rep,name=status" json:"status,omitempty"`
	SearchWord             *google_protobuf.StringValue   `protobuf:"bytes,3,opt,name=search_word,json=searchWord" json:"search_word,omitempty"`
	Owner                  []*google_protobuf.StringValue `protobuf:"bytes,4,rep,name=owner" json:"owner,omitempty"`
	Limit                  *google_protobuf.UInt32Value   `protobuf:"bytes,5,opt,name=limit" json:"limit,omitempty"`
	Offset                 *google_protobuf.UInt32Value   `protobuf:"bytes,6,opt,name=offset" json:"offset,omitempty"`
	Verbose                *google_protobuf.UInt32Value   `protobuf:"bytes,7,opt,name=verbose" json:"verbose,omitempty"`
}

func (m *DescribeRuntimeEnvCredentialsRequset) Reset()         { *m = DescribeRuntimeEnvCredentialsRequset{} }
func (m *DescribeRuntimeEnvCredentialsRequset) String() string { return proto.CompactTextString(m) }
func (*DescribeRuntimeEnvCredentialsRequset) ProtoMessage()    {}
func (*DescribeRuntimeEnvCredentialsRequset) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{12}
}

func (m *DescribeRuntimeEnvCredentialsRequset) GetRuntimeEnvCredentialId() []*google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvCredentialId
	}
	return nil
}

func (m *DescribeRuntimeEnvCredentialsRequset) GetStatus() []*google_protobuf.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeRuntimeEnvCredentialsRequset) GetSearchWord() *google_protobuf.StringValue {
	if m != nil {
		return m.SearchWord
	}
	return nil
}

func (m *DescribeRuntimeEnvCredentialsRequset) GetOwner() []*google_protobuf.StringValue {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *DescribeRuntimeEnvCredentialsRequset) GetLimit() *google_protobuf.UInt32Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *DescribeRuntimeEnvCredentialsRequset) GetOffset() *google_protobuf.UInt32Value {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *DescribeRuntimeEnvCredentialsRequset) GetVerbose() *google_protobuf.UInt32Value {
	if m != nil {
		return m.Verbose
	}
	return nil
}

type DescribeRuntimeEnvCredentialsResponse struct {
	TotalCount              *google_protobuf.UInt32Value `protobuf:"bytes,1,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	RuntimeEnvCredentialSet []*RuntimeEnvCredential      `protobuf:"bytes,2,rep,name=runtime_env_credential_set,json=runtimeEnvCredentialSet" json:"runtime_env_credential_set,omitempty"`
}

func (m *DescribeRuntimeEnvCredentialsResponse) Reset()         { *m = DescribeRuntimeEnvCredentialsResponse{} }
func (m *DescribeRuntimeEnvCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeRuntimeEnvCredentialsResponse) ProtoMessage()    {}
func (*DescribeRuntimeEnvCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{13}
}

func (m *DescribeRuntimeEnvCredentialsResponse) GetTotalCount() *google_protobuf.UInt32Value {
	if m != nil {
		return m.TotalCount
	}
	return nil
}

func (m *DescribeRuntimeEnvCredentialsResponse) GetRuntimeEnvCredentialSet() []*RuntimeEnvCredential {
	if m != nil {
		return m.RuntimeEnvCredentialSet
	}
	return nil
}

type ModifyRuntimeEnvCredentialRequest struct {
	RuntimeEnvCredentialId *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=runtime_env_credential_id,json=runtimeEnvCredentialId" json:"runtime_env_credential_id,omitempty"`
	Name                   *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description            *google_protobuf.StringValue `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Content                map[string]string            `protobuf:"bytes,4,rep,name=content" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ModifyRuntimeEnvCredentialRequest) Reset()         { *m = ModifyRuntimeEnvCredentialRequest{} }
func (m *ModifyRuntimeEnvCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyRuntimeEnvCredentialRequest) ProtoMessage()    {}
func (*ModifyRuntimeEnvCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{14}
}

func (m *ModifyRuntimeEnvCredentialRequest) GetRuntimeEnvCredentialId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvCredentialId
	}
	return nil
}

func (m *ModifyRuntimeEnvCredentialRequest) GetName() *google_protobuf.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ModifyRuntimeEnvCredentialRequest) GetDescription() *google_protobuf.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ModifyRuntimeEnvCredentialRequest) GetContent() map[string]string {
	if m != nil {
		return m.Content
	}
	return nil
}

type ModifyRuntimeEnvCredentialResponse struct {
	RuntimeEnvCredential *RuntimeEnvCredential `protobuf:"bytes,1,opt,name=runtime_env_credential,json=runtimeEnvCredential" json:"runtime_env_credential,omitempty"`
}

func (m *ModifyRuntimeEnvCredentialResponse) Reset()         { *m = ModifyRuntimeEnvCredentialResponse{} }
func (m *ModifyRuntimeEnvCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyRuntimeEnvCredentialResponse) ProtoMessage()    {}
func (*ModifyRuntimeEnvCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{15}
}

func (m *ModifyRuntimeEnvCredentialResponse) GetRuntimeEnvCredential() *RuntimeEnvCredential {
	if m != nil {
		return m.RuntimeEnvCredential
	}
	return nil
}

type DeleteRuntimeEnvCredentialRequset struct {
	RuntimeEnvCredentialId *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=runtime_env_credential_id,json=runtimeEnvCredentialId" json:"runtime_env_credential_id,omitempty"`
}

func (m *DeleteRuntimeEnvCredentialRequset) Reset()         { *m = DeleteRuntimeEnvCredentialRequset{} }
func (m *DeleteRuntimeEnvCredentialRequset) String() string { return proto.CompactTextString(m) }
func (*DeleteRuntimeEnvCredentialRequset) ProtoMessage()    {}
func (*DeleteRuntimeEnvCredentialRequset) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{16}
}

func (m *DeleteRuntimeEnvCredentialRequset) GetRuntimeEnvCredentialId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvCredentialId
	}
	return nil
}

type DeleteRuntimeEnvCredentialResponse struct {
	RuntimeEnvCredential *RuntimeEnvCredential `protobuf:"bytes,1,opt,name=runtime_env_credential,json=runtimeEnvCredential" json:"runtime_env_credential,omitempty"`
}

func (m *DeleteRuntimeEnvCredentialResponse) Reset()         { *m = DeleteRuntimeEnvCredentialResponse{} }
func (m *DeleteRuntimeEnvCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRuntimeEnvCredentialResponse) ProtoMessage()    {}
func (*DeleteRuntimeEnvCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{17}
}

func (m *DeleteRuntimeEnvCredentialResponse) GetRuntimeEnvCredential() *RuntimeEnvCredential {
	if m != nil {
		return m.RuntimeEnvCredential
	}
	return nil
}

type AttachCredentialToRuntimeEnvRequset struct {
	RuntimeEnvCredentialId *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=runtime_env_credential_id,json=runtimeEnvCredentialId" json:"runtime_env_credential_id,omitempty"`
	RuntimeEnvId           *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=runtime_env_id,json=runtimeEnvId" json:"runtime_env_id,omitempty"`
}

func (m *AttachCredentialToRuntimeEnvRequset) Reset()         { *m = AttachCredentialToRuntimeEnvRequset{} }
func (m *AttachCredentialToRuntimeEnvRequset) String() string { return proto.CompactTextString(m) }
func (*AttachCredentialToRuntimeEnvRequset) ProtoMessage()    {}
func (*AttachCredentialToRuntimeEnvRequset) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{18}
}

func (m *AttachCredentialToRuntimeEnvRequset) GetRuntimeEnvCredentialId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvCredentialId
	}
	return nil
}

func (m *AttachCredentialToRuntimeEnvRequset) GetRuntimeEnvId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvId
	}
	return nil
}

type AttachCredentialToRuntimeEnvResponse struct {
	RuntimeEnvCredentialId *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=runtime_env_credential_id,json=runtimeEnvCredentialId" json:"runtime_env_credential_id,omitempty"`
	RuntimeEnvId           *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=runtime_env_id,json=runtimeEnvId" json:"runtime_env_id,omitempty"`
}

func (m *AttachCredentialToRuntimeEnvResponse) Reset()         { *m = AttachCredentialToRuntimeEnvResponse{} }
func (m *AttachCredentialToRuntimeEnvResponse) String() string { return proto.CompactTextString(m) }
func (*AttachCredentialToRuntimeEnvResponse) ProtoMessage()    {}
func (*AttachCredentialToRuntimeEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{19}
}

func (m *AttachCredentialToRuntimeEnvResponse) GetRuntimeEnvCredentialId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvCredentialId
	}
	return nil
}

func (m *AttachCredentialToRuntimeEnvResponse) GetRuntimeEnvId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvId
	}
	return nil
}

type DetachCredentialFromRuntimeEnvRequset struct {
	RuntimeEnvCredentialId *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=runtime_env_credential_id,json=runtimeEnvCredentialId" json:"runtime_env_credential_id,omitempty"`
	RuntimeEnvId           *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=runtime_env_id,json=runtimeEnvId" json:"runtime_env_id,omitempty"`
}

func (m *DetachCredentialFromRuntimeEnvRequset) Reset()         { *m = DetachCredentialFromRuntimeEnvRequset{} }
func (m *DetachCredentialFromRuntimeEnvRequset) String() string { return proto.CompactTextString(m) }
func (*DetachCredentialFromRuntimeEnvRequset) ProtoMessage()    {}
func (*DetachCredentialFromRuntimeEnvRequset) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{20}
}

func (m *DetachCredentialFromRuntimeEnvRequset) GetRuntimeEnvCredentialId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvCredentialId
	}
	return nil
}

func (m *DetachCredentialFromRuntimeEnvRequset) GetRuntimeEnvId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvId
	}
	return nil
}

type DetachCredentialFromRuntimeEnvResponse struct {
	RuntimeEnvCredentialId *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=runtime_env_credential_id,json=runtimeEnvCredentialId" json:"runtime_env_credential_id,omitempty"`
	RuntimeEnvId           *google_protobuf.StringValue `protobuf:"bytes,2,opt,name=runtime_env_id,json=runtimeEnvId" json:"runtime_env_id,omitempty"`
}

func (m *DetachCredentialFromRuntimeEnvResponse) Reset() {
	*m = DetachCredentialFromRuntimeEnvResponse{}
}
func (m *DetachCredentialFromRuntimeEnvResponse) String() string { return proto.CompactTextString(m) }
func (*DetachCredentialFromRuntimeEnvResponse) ProtoMessage()    {}
func (*DetachCredentialFromRuntimeEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor5, []int{21}
}

func (m *DetachCredentialFromRuntimeEnvResponse) GetRuntimeEnvCredentialId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvCredentialId
	}
	return nil
}

func (m *DetachCredentialFromRuntimeEnvResponse) GetRuntimeEnvId() *google_protobuf.StringValue {
	if m != nil {
		return m.RuntimeEnvId
	}
	return nil
}

func init() {
	proto.RegisterType((*RuntimeEnv)(nil), "openpitrix.RuntimeEnv")
	proto.RegisterType((*CreateRuntimeEnvRequest)(nil), "openpitrix.CreateRuntimeEnvRequest")
	proto.RegisterType((*CreateRuntimeEnvResponse)(nil), "openpitrix.CreateRuntimeEnvResponse")
	proto.RegisterType((*DescribeRuntimeEnvsRequest)(nil), "openpitrix.DescribeRuntimeEnvsRequest")
	proto.RegisterType((*DescribeRuntimeEnvsResponse)(nil), "openpitrix.DescribeRuntimeEnvsResponse")
	proto.RegisterType((*ModifyRuntimeEnvRequest)(nil), "openpitrix.ModifyRuntimeEnvRequest")
	proto.RegisterType((*ModifyRuntimeEnvResponse)(nil), "openpitrix.ModifyRuntimeEnvResponse")
	proto.RegisterType((*DeleteRuntimeEnvRequest)(nil), "openpitrix.DeleteRuntimeEnvRequest")
	proto.RegisterType((*DeleteRuntimeEnvResponse)(nil), "openpitrix.DeleteRuntimeEnvResponse")
	proto.RegisterType((*RuntimeEnvCredential)(nil), "openpitrix.RuntimeEnvCredential")
	proto.RegisterType((*CreateRuntimeEnvCredentialRequset)(nil), "openpitrix.CreateRuntimeEnvCredentialRequset")
	proto.RegisterType((*CreateRuntimeEnvCredentialResponse)(nil), "openpitrix.CreateRuntimeEnvCredentialResponse")
	proto.RegisterType((*DescribeRuntimeEnvCredentialsRequset)(nil), "openpitrix.DescribeRuntimeEnvCredentialsRequset")
	proto.RegisterType((*DescribeRuntimeEnvCredentialsResponse)(nil), "openpitrix.DescribeRuntimeEnvCredentialsResponse")
	proto.RegisterType((*ModifyRuntimeEnvCredentialRequest)(nil), "openpitrix.ModifyRuntimeEnvCredentialRequest")
	proto.RegisterType((*ModifyRuntimeEnvCredentialResponse)(nil), "openpitrix.ModifyRuntimeEnvCredentialResponse")
	proto.RegisterType((*DeleteRuntimeEnvCredentialRequset)(nil), "openpitrix.DeleteRuntimeEnvCredentialRequset")
	proto.RegisterType((*DeleteRuntimeEnvCredentialResponse)(nil), "openpitrix.DeleteRuntimeEnvCredentialResponse")
	proto.RegisterType((*AttachCredentialToRuntimeEnvRequset)(nil), "openpitrix.AttachCredentialToRuntimeEnvRequset")
	proto.RegisterType((*AttachCredentialToRuntimeEnvResponse)(nil), "openpitrix.AttachCredentialToRuntimeEnvResponse")
	proto.RegisterType((*DetachCredentialFromRuntimeEnvRequset)(nil), "openpitrix.DetachCredentialFromRuntimeEnvRequset")
	proto.RegisterType((*DetachCredentialFromRuntimeEnvResponse)(nil), "openpitrix.DetachCredentialFromRuntimeEnvResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RuntimeEnvManager service

type RuntimeEnvManagerClient interface {
	CreateRuntimeEnv(ctx context.Context, in *CreateRuntimeEnvRequest, opts ...grpc.CallOption) (*CreateRuntimeEnvResponse, error)
	DescribeRuntimeEnvs(ctx context.Context, in *DescribeRuntimeEnvsRequest, opts ...grpc.CallOption) (*DescribeRuntimeEnvsResponse, error)
	ModifyRuntimeEnv(ctx context.Context, in *ModifyRuntimeEnvRequest, opts ...grpc.CallOption) (*ModifyRuntimeEnvResponse, error)
	DeleteRuntimeEnv(ctx context.Context, in *DeleteRuntimeEnvRequest, opts ...grpc.CallOption) (*DeleteRuntimeEnvResponse, error)
	CreateRuntimeEnvCredential(ctx context.Context, in *CreateRuntimeEnvCredentialRequset, opts ...grpc.CallOption) (*CreateRuntimeEnvCredentialResponse, error)
	DescribeRuntimeEnvCredentials(ctx context.Context, in *DescribeRuntimeEnvCredentialsRequset, opts ...grpc.CallOption) (*DescribeRuntimeEnvCredentialsResponse, error)
	ModifyRuntimeEnvCredential(ctx context.Context, in *ModifyRuntimeEnvCredentialRequest, opts ...grpc.CallOption) (*ModifyRuntimeEnvCredentialResponse, error)
	DeleteRuntimeEnvCredential(ctx context.Context, in *DeleteRuntimeEnvCredentialRequset, opts ...grpc.CallOption) (*DeleteRuntimeEnvCredentialResponse, error)
	AttachCredentialToRuntimeEnv(ctx context.Context, in *AttachCredentialToRuntimeEnvRequset, opts ...grpc.CallOption) (*AttachCredentialToRuntimeEnvResponse, error)
	DetachCredentialFromRuntimeEnv(ctx context.Context, in *DetachCredentialFromRuntimeEnvRequset, opts ...grpc.CallOption) (*DetachCredentialFromRuntimeEnvResponse, error)
}

type runtimeEnvManagerClient struct {
	cc *grpc.ClientConn
}

func NewRuntimeEnvManagerClient(cc *grpc.ClientConn) RuntimeEnvManagerClient {
	return &runtimeEnvManagerClient{cc}
}

func (c *runtimeEnvManagerClient) CreateRuntimeEnv(ctx context.Context, in *CreateRuntimeEnvRequest, opts ...grpc.CallOption) (*CreateRuntimeEnvResponse, error) {
	out := new(CreateRuntimeEnvResponse)
	err := grpc.Invoke(ctx, "/openpitrix.RuntimeEnvManager/CreateRuntimeEnv", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeEnvManagerClient) DescribeRuntimeEnvs(ctx context.Context, in *DescribeRuntimeEnvsRequest, opts ...grpc.CallOption) (*DescribeRuntimeEnvsResponse, error) {
	out := new(DescribeRuntimeEnvsResponse)
	err := grpc.Invoke(ctx, "/openpitrix.RuntimeEnvManager/DescribeRuntimeEnvs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeEnvManagerClient) ModifyRuntimeEnv(ctx context.Context, in *ModifyRuntimeEnvRequest, opts ...grpc.CallOption) (*ModifyRuntimeEnvResponse, error) {
	out := new(ModifyRuntimeEnvResponse)
	err := grpc.Invoke(ctx, "/openpitrix.RuntimeEnvManager/ModifyRuntimeEnv", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeEnvManagerClient) DeleteRuntimeEnv(ctx context.Context, in *DeleteRuntimeEnvRequest, opts ...grpc.CallOption) (*DeleteRuntimeEnvResponse, error) {
	out := new(DeleteRuntimeEnvResponse)
	err := grpc.Invoke(ctx, "/openpitrix.RuntimeEnvManager/DeleteRuntimeEnv", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeEnvManagerClient) CreateRuntimeEnvCredential(ctx context.Context, in *CreateRuntimeEnvCredentialRequset, opts ...grpc.CallOption) (*CreateRuntimeEnvCredentialResponse, error) {
	out := new(CreateRuntimeEnvCredentialResponse)
	err := grpc.Invoke(ctx, "/openpitrix.RuntimeEnvManager/CreateRuntimeEnvCredential", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeEnvManagerClient) DescribeRuntimeEnvCredentials(ctx context.Context, in *DescribeRuntimeEnvCredentialsRequset, opts ...grpc.CallOption) (*DescribeRuntimeEnvCredentialsResponse, error) {
	out := new(DescribeRuntimeEnvCredentialsResponse)
	err := grpc.Invoke(ctx, "/openpitrix.RuntimeEnvManager/DescribeRuntimeEnvCredentials", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeEnvManagerClient) ModifyRuntimeEnvCredential(ctx context.Context, in *ModifyRuntimeEnvCredentialRequest, opts ...grpc.CallOption) (*ModifyRuntimeEnvCredentialResponse, error) {
	out := new(ModifyRuntimeEnvCredentialResponse)
	err := grpc.Invoke(ctx, "/openpitrix.RuntimeEnvManager/ModifyRuntimeEnvCredential", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeEnvManagerClient) DeleteRuntimeEnvCredential(ctx context.Context, in *DeleteRuntimeEnvCredentialRequset, opts ...grpc.CallOption) (*DeleteRuntimeEnvCredentialResponse, error) {
	out := new(DeleteRuntimeEnvCredentialResponse)
	err := grpc.Invoke(ctx, "/openpitrix.RuntimeEnvManager/DeleteRuntimeEnvCredential", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeEnvManagerClient) AttachCredentialToRuntimeEnv(ctx context.Context, in *AttachCredentialToRuntimeEnvRequset, opts ...grpc.CallOption) (*AttachCredentialToRuntimeEnvResponse, error) {
	out := new(AttachCredentialToRuntimeEnvResponse)
	err := grpc.Invoke(ctx, "/openpitrix.RuntimeEnvManager/AttachCredentialToRuntimeEnv", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeEnvManagerClient) DetachCredentialFromRuntimeEnv(ctx context.Context, in *DetachCredentialFromRuntimeEnvRequset, opts ...grpc.CallOption) (*DetachCredentialFromRuntimeEnvResponse, error) {
	out := new(DetachCredentialFromRuntimeEnvResponse)
	err := grpc.Invoke(ctx, "/openpitrix.RuntimeEnvManager/DetachCredentialFromRuntimeEnv", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RuntimeEnvManager service

type RuntimeEnvManagerServer interface {
	CreateRuntimeEnv(context.Context, *CreateRuntimeEnvRequest) (*CreateRuntimeEnvResponse, error)
	DescribeRuntimeEnvs(context.Context, *DescribeRuntimeEnvsRequest) (*DescribeRuntimeEnvsResponse, error)
	ModifyRuntimeEnv(context.Context, *ModifyRuntimeEnvRequest) (*ModifyRuntimeEnvResponse, error)
	DeleteRuntimeEnv(context.Context, *DeleteRuntimeEnvRequest) (*DeleteRuntimeEnvResponse, error)
	CreateRuntimeEnvCredential(context.Context, *CreateRuntimeEnvCredentialRequset) (*CreateRuntimeEnvCredentialResponse, error)
	DescribeRuntimeEnvCredentials(context.Context, *DescribeRuntimeEnvCredentialsRequset) (*DescribeRuntimeEnvCredentialsResponse, error)
	ModifyRuntimeEnvCredential(context.Context, *ModifyRuntimeEnvCredentialRequest) (*ModifyRuntimeEnvCredentialResponse, error)
	DeleteRuntimeEnvCredential(context.Context, *DeleteRuntimeEnvCredentialRequset) (*DeleteRuntimeEnvCredentialResponse, error)
	AttachCredentialToRuntimeEnv(context.Context, *AttachCredentialToRuntimeEnvRequset) (*AttachCredentialToRuntimeEnvResponse, error)
	DetachCredentialFromRuntimeEnv(context.Context, *DetachCredentialFromRuntimeEnvRequset) (*DetachCredentialFromRuntimeEnvResponse, error)
}

func RegisterRuntimeEnvManagerServer(s *grpc.Server, srv RuntimeEnvManagerServer) {
	s.RegisterService(&_RuntimeEnvManager_serviceDesc, srv)
}

func _RuntimeEnvManager_CreateRuntimeEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuntimeEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeEnvManagerServer).CreateRuntimeEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.RuntimeEnvManager/CreateRuntimeEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeEnvManagerServer).CreateRuntimeEnv(ctx, req.(*CreateRuntimeEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeEnvManager_DescribeRuntimeEnvs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRuntimeEnvsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeEnvManagerServer).DescribeRuntimeEnvs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.RuntimeEnvManager/DescribeRuntimeEnvs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeEnvManagerServer).DescribeRuntimeEnvs(ctx, req.(*DescribeRuntimeEnvsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeEnvManager_ModifyRuntimeEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyRuntimeEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeEnvManagerServer).ModifyRuntimeEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.RuntimeEnvManager/ModifyRuntimeEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeEnvManagerServer).ModifyRuntimeEnv(ctx, req.(*ModifyRuntimeEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeEnvManager_DeleteRuntimeEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuntimeEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeEnvManagerServer).DeleteRuntimeEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.RuntimeEnvManager/DeleteRuntimeEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeEnvManagerServer).DeleteRuntimeEnv(ctx, req.(*DeleteRuntimeEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeEnvManager_CreateRuntimeEnvCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuntimeEnvCredentialRequset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeEnvManagerServer).CreateRuntimeEnvCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.RuntimeEnvManager/CreateRuntimeEnvCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeEnvManagerServer).CreateRuntimeEnvCredential(ctx, req.(*CreateRuntimeEnvCredentialRequset))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeEnvManager_DescribeRuntimeEnvCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRuntimeEnvCredentialsRequset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeEnvManagerServer).DescribeRuntimeEnvCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.RuntimeEnvManager/DescribeRuntimeEnvCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeEnvManagerServer).DescribeRuntimeEnvCredentials(ctx, req.(*DescribeRuntimeEnvCredentialsRequset))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeEnvManager_ModifyRuntimeEnvCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyRuntimeEnvCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeEnvManagerServer).ModifyRuntimeEnvCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.RuntimeEnvManager/ModifyRuntimeEnvCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeEnvManagerServer).ModifyRuntimeEnvCredential(ctx, req.(*ModifyRuntimeEnvCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeEnvManager_DeleteRuntimeEnvCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuntimeEnvCredentialRequset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeEnvManagerServer).DeleteRuntimeEnvCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.RuntimeEnvManager/DeleteRuntimeEnvCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeEnvManagerServer).DeleteRuntimeEnvCredential(ctx, req.(*DeleteRuntimeEnvCredentialRequset))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeEnvManager_AttachCredentialToRuntimeEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachCredentialToRuntimeEnvRequset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeEnvManagerServer).AttachCredentialToRuntimeEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.RuntimeEnvManager/AttachCredentialToRuntimeEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeEnvManagerServer).AttachCredentialToRuntimeEnv(ctx, req.(*AttachCredentialToRuntimeEnvRequset))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeEnvManager_DetachCredentialFromRuntimeEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachCredentialFromRuntimeEnvRequset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeEnvManagerServer).DetachCredentialFromRuntimeEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/openpitrix.RuntimeEnvManager/DetachCredentialFromRuntimeEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeEnvManagerServer).DetachCredentialFromRuntimeEnv(ctx, req.(*DetachCredentialFromRuntimeEnvRequset))
	}
	return interceptor(ctx, in, info, handler)
}

var _RuntimeEnvManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "openpitrix.RuntimeEnvManager",
	HandlerType: (*RuntimeEnvManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRuntimeEnv",
			Handler:    _RuntimeEnvManager_CreateRuntimeEnv_Handler,
		},
		{
			MethodName: "DescribeRuntimeEnvs",
			Handler:    _RuntimeEnvManager_DescribeRuntimeEnvs_Handler,
		},
		{
			MethodName: "ModifyRuntimeEnv",
			Handler:    _RuntimeEnvManager_ModifyRuntimeEnv_Handler,
		},
		{
			MethodName: "DeleteRuntimeEnv",
			Handler:    _RuntimeEnvManager_DeleteRuntimeEnv_Handler,
		},
		{
			MethodName: "CreateRuntimeEnvCredential",
			Handler:    _RuntimeEnvManager_CreateRuntimeEnvCredential_Handler,
		},
		{
			MethodName: "DescribeRuntimeEnvCredentials",
			Handler:    _RuntimeEnvManager_DescribeRuntimeEnvCredentials_Handler,
		},
		{
			MethodName: "ModifyRuntimeEnvCredential",
			Handler:    _RuntimeEnvManager_ModifyRuntimeEnvCredential_Handler,
		},
		{
			MethodName: "DeleteRuntimeEnvCredential",
			Handler:    _RuntimeEnvManager_DeleteRuntimeEnvCredential_Handler,
		},
		{
			MethodName: "AttachCredentialToRuntimeEnv",
			Handler:    _RuntimeEnvManager_AttachCredentialToRuntimeEnv_Handler,
		},
		{
			MethodName: "DetachCredentialFromRuntimeEnv",
			Handler:    _RuntimeEnvManager_DetachCredentialFromRuntimeEnv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime_env.proto",
}

func init() { proto.RegisterFile("runtime_env.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 1374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x59, 0x4b, 0x6f, 0x1b, 0x55,
	0x1b, 0xd6, 0xf8, 0x92, 0xb4, 0xaf, 0xfb, 0xf5, 0x4b, 0x0f, 0x69, 0x63, 0xa6, 0x97, 0x38, 0x93,
	0x50, 0x50, 0x20, 0x76, 0xe2, 0x22, 0xa8, 0x0c, 0xad, 0x94, 0x26, 0x85, 0x66, 0x51, 0x51, 0x39,
	0x69, 0x2b, 0x21, 0x55, 0xd1, 0xd8, 0x73, 0xe2, 0x4c, 0x19, 0xcf, 0x99, 0xce, 0x1c, 0x3b, 0x8d,
	0xd4, 0x05, 0x42, 0x42, 0x6c, 0x21, 0xec, 0x10, 0x0b, 0x76, 0xfc, 0x0c, 0x24, 0x20, 0x1b, 0x36,
	0x2c, 0xf8, 0x0b, 0xf0, 0x2b, 0xd8, 0xa0, 0x73, 0x66, 0x9c, 0x39, 0xe3, 0xb9, 0x3a, 0x37, 0x11,
	0x56, 0x49, 0xc6, 0xef, 0x7b, 0xce, 0xf3, 0xbc, 0xd7, 0x67, 0x1c, 0xb8, 0x64, 0xf7, 0x4c, 0xaa,
	0x77, 0xf1, 0x26, 0x36, 0xfb, 0x55, 0xcb, 0x26, 0x94, 0x20, 0x20, 0x16, 0x36, 0x2d, 0x9d, 0xda,
	0xfa, 0x4b, 0xf9, 0x46, 0x87, 0x90, 0x8e, 0x81, 0x6b, 0xfc, 0x93, 0x56, 0x6f, 0xab, 0xb6, 0x63,
	0xab, 0x96, 0x85, 0x6d, 0xc7, 0xb5, 0x95, 0xa7, 0x87, 0x3f, 0x67, 0x67, 0x39, 0x54, 0xed, 0x5a,
	0x9e, 0xc1, 0x35, 0xcf, 0x40, 0xb5, 0xf4, 0x9a, 0x6a, 0x9a, 0x84, 0xaa, 0x54, 0x27, 0xe6, 0xc0,
	0xfd, 0x1d, 0xfe, 0xa3, 0xbd, 0xd0, 0xc1, 0xe6, 0x82, 0xb3, 0xa3, 0x76, 0x3a, 0xd8, 0xae, 0x11,
	0x8b, 0x5b, 0x84, 0xad, 0x95, 0xbf, 0x0b, 0x00, 0x4d, 0x17, 0xee, 0x7d, 0xb3, 0x8f, 0xee, 0xc1,
	0x45, 0x01, 0xfc, 0xa6, 0xae, 0x95, 0xa5, 0x8a, 0xf4, 0x56, 0xa9, 0x7e, 0xad, 0xea, 0xde, 0x59,
	0x1d, 0x80, 0xaa, 0xae, 0x53, 0x5b, 0x37, 0x3b, 0x4f, 0x54, 0xa3, 0x87, 0x9b, 0x17, 0xec, 0x83,
	0x13, 0xd6, 0x34, 0xb4, 0x08, 0x05, 0x53, 0xed, 0xe2, 0x72, 0x2e, 0x83, 0x27, 0xb7, 0x44, 0x77,
	0xa1, 0xa4, 0x61, 0xa7, 0x6d, 0xeb, 0x1c, 0x66, 0x39, 0x9f, 0xc1, 0x51, 0x74, 0x40, 0xab, 0xf0,
	0x7f, 0x11, 0x75, 0xcf, 0x36, 0xca, 0x85, 0x0c, 0x67, 0xfc, 0xcf, 0x87, 0xfd, 0xd8, 0x36, 0xd0,
	0x53, 0x78, 0x5d, 0x3c, 0xa5, 0x6d, 0x63, 0x0d, 0x9b, 0x54, 0x57, 0x0d, 0x16, 0x86, 0x62, 0x86,
	0xf3, 0xae, 0xf8, 0xe7, 0xad, 0x1c, 0x38, 0xaf, 0x69, 0xe8, 0x5d, 0x18, 0x33, 0xd4, 0x16, 0x36,
	0x9c, 0xf2, 0x58, 0x86, 0x53, 0x3c, 0x5b, 0x54, 0x87, 0x22, 0xd9, 0x31, 0xb1, 0x5d, 0x1e, 0xcf,
	0xe0, 0xe4, 0x9a, 0xb2, 0x9b, 0x1c, 0xaa, 0xd2, 0x9e, 0x53, 0x3e, 0x97, 0xe5, 0x26, 0xd7, 0x16,
	0x7d, 0x00, 0xa5, 0xb6, 0x8d, 0x55, 0x8a, 0x37, 0x19, 0xfa, 0xf2, 0x79, 0xee, 0x2a, 0x87, 0x5c,
	0x37, 0x06, 0x65, 0xd8, 0x04, 0xd7, 0x9c, 0x3d, 0x60, 0xce, 0xee, 0x31, 0xae, 0x33, 0xa4, 0x3b,
	0xbb, 0xe6, 0xec, 0x81, 0xf2, 0x55, 0x0e, 0xa6, 0x56, 0xf8, 0x59, 0x7e, 0x0d, 0x36, 0xf1, 0x8b,
	0x1e, 0x76, 0xe8, 0x41, 0x19, 0x49, 0x87, 0x2d, 0xa3, 0xdc, 0xa8, 0x65, 0xe4, 0xe7, 0x29, 0x3f,
	0x42, 0x9e, 0x8e, 0xa5, 0xf8, 0x94, 0x75, 0x28, 0x87, 0x03, 0xe1, 0x58, 0xc4, 0x74, 0x30, 0x7a,
	0x1f, 0x4a, 0xc2, 0x0d, 0x5e, 0x40, 0xae, 0x54, 0xfd, 0x91, 0x52, 0x15, 0x9c, 0xc0, 0x3f, 0x57,
	0xf9, 0x2b, 0x0f, 0xf2, 0x2a, 0x27, 0xd8, 0x12, 0xce, 0x75, 0x06, 0x11, 0x8e, 0x6a, 0xf6, 0xfc,
	0x88, 0xcd, 0xee, 0x57, 0x5c, 0x2e, 0x83, 0xef, 0xa0, 0xe2, 0xee, 0x40, 0xc9, 0xc1, 0xaa, 0xdd,
	0xde, 0xde, 0xdc, 0x21, 0xb6, 0x96, 0x29, 0xdc, 0xe0, 0x3a, 0x3c, 0x25, 0xb6, 0x86, 0x6e, 0xc3,
	0x39, 0x07, 0x1b, 0xb8, 0x4d, 0x89, 0x9d, 0x29, 0xd6, 0x07, 0xd6, 0x7e, 0x53, 0x15, 0x33, 0xa0,
	0xf5, 0x9a, 0xaa, 0x0e, 0x45, 0x43, 0xef, 0xea, 0x34, 0xb6, 0x7b, 0x1f, 0xaf, 0x99, 0xf4, 0x56,
	0xdd, 0xf3, 0xe1, 0xa6, 0x2c, 0x2c, 0x64, 0x6b, 0xcb, 0xc1, 0x34, 0xb6, 0x7b, 0x45, 0x27, 0xcf,
	0x16, 0xbd, 0x07, 0xe3, 0x7d, 0x6c, 0xb7, 0x88, 0x83, 0x63, 0xfb, 0x57, 0x74, 0x1b, 0x18, 0x2b,
	0xdf, 0x4b, 0x70, 0x35, 0x32, 0xcf, 0x5e, 0x01, 0xdd, 0x81, 0x12, 0x25, 0x54, 0x35, 0x36, 0xdb,
	0xa4, 0x67, 0xd2, 0xd8, 0x8e, 0x12, 0xcf, 0x06, 0xee, 0xb0, 0xc2, 0xec, 0xd1, 0xdd, 0x60, 0x85,
	0x33, 0x56, 0x6e, 0xb2, 0xe3, 0x6a, 0x50, 0xa8, 0xed, 0x75, 0x4c, 0x95, 0x2f, 0x73, 0x30, 0xf5,
	0x90, 0x68, 0xfa, 0xd6, 0x6e, 0xb8, 0xcb, 0xcf, 0xe6, 0xc2, 0xf1, 0x27, 0x45, 0x21, 0xfb, 0xa4,
	0x60, 0x3d, 0x1e, 0x0e, 0xc3, 0x51, 0x7b, 0xfc, 0x19, 0x4c, 0xad, 0x62, 0x03, 0x47, 0x4d, 0xd0,
	0x63, 0x88, 0x2d, 0xc3, 0x1c, 0x3e, 0xfe, 0xa8, 0x98, 0xbf, 0x2e, 0xc2, 0x64, 0x33, 0x62, 0x57,
	0x26, 0xaf, 0x60, 0xe9, 0x08, 0x2b, 0xf8, 0xf4, 0x4b, 0xe4, 0x63, 0x18, 0x6f, 0x13, 0x93, 0x62,
	0x93, 0x96, 0x0b, 0xbc, 0x59, 0x16, 0xa2, 0x03, 0xe3, 0xc3, 0xac, 0xae, 0xb8, 0xf6, 0xf7, 0x4d,
	0x6a, 0xef, 0x36, 0x07, 0xde, 0xe2, 0xc8, 0xca, 0xac, 0x03, 0x86, 0x76, 0x92, 0xae, 0x31, 0xe9,
	0x91, 0x1f, 0x65, 0x27, 0xad, 0x69, 0x8e, 0x30, 0xdb, 0xc7, 0xcf, 0x82, 0x9a, 0x90, 0x1b, 0x70,
	0x41, 0x0c, 0x21, 0x9a, 0x80, 0xfc, 0x67, 0x78, 0x97, 0xd7, 0xcd, 0xf9, 0x26, 0xfb, 0x15, 0x4d,
	0x42, 0xb1, 0xcf, 0xc0, 0xf2, 0x3a, 0x38, 0xdf, 0x74, 0xff, 0x68, 0xe4, 0x6e, 0x4b, 0xca, 0x8f,
	0x39, 0x98, 0x19, 0x5e, 0xc0, 0x7e, 0x6a, 0x58, 0x47, 0xb1, 0x01, 0x7d, 0xfa, 0x9a, 0x64, 0xc3,
	0x2f, 0xa3, 0x3c, 0xcf, 0x60, 0x43, 0x2c, 0xa3, 0x54, 0xc4, 0xd1, 0x35, 0x75, 0xa4, 0x48, 0xbd,
	0x02, 0x25, 0xe9, 0x5a, 0x6f, 0x36, 0x3c, 0x81, 0x2b, 0xd1, 0x9d, 0xec, 0xc5, 0xae, 0x92, 0xd6,
	0x0d, 0xcd, 0xc9, 0xa8, 0x56, 0x56, 0x7e, 0xcb, 0xc3, 0x5c, 0x78, 0xd5, 0xf9, 0x06, 0xce, 0x20,
	0x55, 0x29, 0xa3, 0x24, 0x7f, 0x14, 0x35, 0x7f, 0xfa, 0x8a, 0xe7, 0x60, 0x08, 0x14, 0x0e, 0xa1,
	0x5b, 0x8a, 0x87, 0xd1, 0x2d, 0x63, 0x87, 0xd3, 0x2d, 0xe3, 0xa3, 0xe8, 0x96, 0x7d, 0x09, 0xde,
	0x48, 0x49, 0xe6, 0xf1, 0x28, 0x98, 0x67, 0x20, 0xc7, 0x14, 0x83, 0x2f, 0x66, 0xd2, 0x2b, 0x72,
	0x2a, 0xaa, 0x22, 0x98, 0xc0, 0xf9, 0x3c, 0x0f, 0x33, 0xc3, 0x9b, 0x3d, 0xd8, 0x8a, 0x6c, 0x1d,
	0xff, 0x87, 0x96, 0xdb, 0xc6, 0xf0, 0x72, 0x0b, 0x4c, 0xa5, 0xd4, 0x50, 0x9c, 0xcc, 0x54, 0x4a,
	0xba, 0xf6, 0x84, 0xa7, 0xd2, 0x2b, 0x98, 0x19, 0x56, 0x49, 0xe1, 0xe5, 0x71, 0x52, 0xf9, 0x67,
	0xdc, 0x93, 0x6e, 0x3f, 0x61, 0xee, 0x3f, 0x4b, 0x30, 0xbb, 0x4c, 0xa9, 0xda, 0xde, 0xf6, 0x1f,
	0x6e, 0x90, 0xa0, 0x1a, 0x3d, 0x49, 0xfa, 0x11, 0x32, 0x37, 0x37, 0xb2, 0xcc, 0xfd, 0x45, 0x82,
	0xb9, 0x64, 0x12, 0x5e, 0x14, 0xff, 0xd5, 0x2c, 0x7e, 0xe5, 0xf3, 0x34, 0xc8, 0xe2, 0x23, 0x9b,
	0x74, 0xcf, 0x58, 0x32, 0xf6, 0x25, 0xb8, 0x99, 0x46, 0xe3, 0x0c, 0xa4, 0xa3, 0xfe, 0xc3, 0x45,
	0xb8, 0xe4, 0x63, 0x7e, 0xa8, 0x9a, 0x6a, 0x07, 0xdb, 0xe8, 0x1b, 0x09, 0x26, 0x86, 0x05, 0x14,
	0x9a, 0x4d, 0x52, 0x75, 0xde, 0xd4, 0x94, 0xe7, 0x92, 0x8d, 0xdc, 0x90, 0x28, 0xf5, 0xbd, 0xe5,
	0x49, 0x84, 0x5c, 0x4d, 0x5d, 0xf1, 0xf0, 0x54, 0xb0, 0xd9, 0xff, 0xe2, 0x8f, 0x3f, 0xbf, 0xcd,
	0x5d, 0x56, 0x26, 0x6a, 0xfd, 0xa5, 0x9a, 0x40, 0xcd, 0x69, 0x48, 0xf3, 0xe8, 0x3b, 0x09, 0x5e,
	0x8b, 0xf8, 0x02, 0x01, 0xdd, 0x14, 0x6f, 0x8c, 0xff, 0x26, 0x49, 0x7e, 0x33, 0xd5, 0xce, 0x07,
	0x37, 0x85, 0x2e, 0x6b, 0x9e, 0x85, 0x08, 0xcf, 0xe1, 0xf8, 0x10, 0x0a, 0xe1, 0xe3, 0x01, 0x1b,
	0x9e, 0xed, 0xc1, 0x80, 0xc5, 0x7c, 0xb9, 0x10, 0x0c, 0x58, 0xdc, 0xab, 0xb7, 0x17, 0xb0, 0x2e,
	0xff, 0x38, 0x1c, 0xb0, 0x7a, 0x64, 0xc0, 0x18, 0xa6, 0xe1, 0x99, 0x1b, 0xc4, 0x14, 0xf3, 0x52,
	0x1e, 0xc4, 0x14, 0xf7, 0x6a, 0x9d, 0x92, 0xc4, 0xf9, 0x48, 0x4c, 0xfb, 0x12, 0xc8, 0xf1, 0xca,
	0x1c, 0x2d, 0x8c, 0xf4, 0xe2, 0x20, 0x57, 0xb3, 0x9a, 0x7b, 0x88, 0x1f, 0xec, 0x2d, 0x4f, 0xa3,
	0xeb, 0x61, 0xc4, 0x15, 0xbf, 0x27, 0x39, 0xf8, 0x8a, 0x72, 0x75, 0x08, 0xbc, 0xd0, 0xb5, 0x9c,
	0xc7, 0xef, 0x12, 0x5c, 0x4f, 0x54, 0x85, 0x68, 0x31, 0xb9, 0xdc, 0xc2, 0x6f, 0x03, 0xf2, 0xd2,
	0x08, 0x1e, 0x1e, 0xa1, 0xb5, 0xbd, 0xe5, 0x59, 0x34, 0x13, 0x55, 0xaa, 0x8c, 0x92, 0x39, 0xb0,
	0xe7, 0xa4, 0xae, 0xa3, 0x24, 0x52, 0x3c, 0x33, 0xf1, 0xea, 0x24, 0x98, 0x99, 0x54, 0xf1, 0x14,
	0xcc, 0x4c, 0xba, 0xe8, 0xf1, 0x32, 0x13, 0xae, 0xef, 0x50, 0x66, 0xea, 0x69, 0x99, 0x61, 0x3c,
	0xe2, 0x95, 0x46, 0x90, 0x47, 0xaa, 0x1e, 0x0a, 0xf2, 0x48, 0x17, 0x30, 0xd9, 0x79, 0xcc, 0xa7,
	0xf1, 0xf8, 0x49, 0x82, 0x6b, 0x49, 0xdb, 0x1e, 0xd5, 0x44, 0x68, 0x19, 0xc4, 0x8d, 0xbc, 0x98,
	0xdd, 0xc1, 0x63, 0xf3, 0x61, 0x52, 0x87, 0x4f, 0x2b, 0x32, 0xa3, 0x20, 0xac, 0x33, 0x81, 0x8d,
	0x97, 0x89, 0x1b, 0xc9, 0x2b, 0x12, 0x0d, 0x95, 0x7c, 0x06, 0x55, 0x20, 0xd7, 0x47, 0x71, 0x09,
	0xf0, 0xd0, 0xb8, 0x71, 0x98, 0xc7, 0x7c, 0x32, 0x8f, 0x7b, 0x2f, 0xf7, 0x96, 0x5f, 0xa0, 0x07,
	0x80, 0x3e, 0xb1, 0xb0, 0xf9, 0x88, 0xdf, 0x5b, 0x79, 0x64, 0x93, 0xe7, 0xb8, 0x4d, 0x95, 0xb7,
	0xa3, 0x9e, 0xa2, 0xcb, 0xdb, 0x94, 0x5a, 0x4e, 0xa3, 0x56, 0x13, 0x90, 0xea, 0xa4, 0x5e, 0x5c,
	0xac, 0x2e, 0x56, 0x97, 0xe6, 0x25, 0xa9, 0x3e, 0xa1, 0x5a, 0x96, 0xa1, 0xb7, 0xf9, 0x3f, 0x39,
	0x6b, 0xcf, 0x1d, 0x62, 0x36, 0x42, 0x4f, 0x3e, 0xcd, 0x59, 0xad, 0xd6, 0x18, 0x5f, 0xe0, 0xb7,
	0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x2f, 0x10, 0x83, 0xad, 0x1d, 0x00, 0x00,
}
