# Copyright 2017 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

default:
	chmod +x ./update_version.sh
	./update_version.sh

clean:
	-rm z_update_version.go
