ALTER TABLE cluster_node
	MODIFY COLUMN role VARCHAR(100) NOT NULL;
ALTER TABLE cluster_common
    MODIFY COLUMN role VARCHAR(100) NOT NULL;
ALTER TABLE cluster_snapshot
    MODIFY COLUMN role VARCHAR(100) NOT NULL;
ALTER TABLE cluster_role
    MODIFY COLUMN role VARCHAR(100) NOT NULL;
ALTER TABLE cluster_loadbalancer
    MODIFY COLUMN role VARCHAR(100) NOT NULL;
