// Code generated by go-swagger; DO NOT EDIT.

package app_runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAppruntimesHandlerFunc turns a function with the right signature into a get appruntimes handler
type GetAppruntimesHandlerFunc func(GetAppruntimesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAppruntimesHandlerFunc) Handle(params GetAppruntimesParams) middleware.Responder {
	return fn(params)
}

// GetAppruntimesHandler interface for that can handle valid get appruntimes params
type GetAppruntimesHandler interface {
	Handle(GetAppruntimesParams) middleware.Responder
}

// NewGetAppruntimes creates a new http.Handler for the get appruntimes operation
func NewGetAppruntimes(ctx *middleware.Context, handler GetAppruntimesHandler) *GetAppruntimes {
	return &GetAppruntimes{Context: ctx, Handler: handler}
}

/*GetAppruntimes swagger:route GET /appruntimes app-runtime getAppruntimes

Gets some app runtimes

Returns a list containing all app runtimes.

*/
type GetAppruntimes struct {
	Context *middleware.Context
	Handler GetAppruntimesHandler
}

func (o *GetAppruntimes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAppruntimesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
